import type {
  ConsentCategoryV2,
  ConsentTemplateV2,
  EducationAssetV2,
} from "./types";

/**
 * Approved Forms V2 — formal consent taxonomy.
 *
 * This taxonomy is intentionally broader than the legacy production library.
 * It introduces a two-level hierarchy:
 *   Category -> Consent Type -> Specialty -> Department -> Template
 *
 * It is seeded from the Saudi enterprise template library but extended with
 * status tracking, risk classification, and witness/guardian/interpreter rules
 * for the V2 prototype.
 */

export const CONSENT_CATEGORIES_V2: ConsentCategoryV2[] = [
  {
    code: "GENERAL_TREATMENT",
    nameEn: "General Treatment Consent",
    nameAr: "الموافقة العامة على العلاج",
    descriptionEn: "Covers routine clinical assessment, treatment, and general medical services.",
    descriptionAr: "تغطي الفحص السريري والعلاج الروتيني والخدمات الطبية العامة.",
    sortOrder: 1,
  },
  {
    code: "SURGICAL",
    nameEn: "Surgical Procedure Consent",
    nameAr: "موافقة الإجراء الجراحي",
    descriptionEn: "Comprehensive surgical consent including risks and intraoperative contingencies.",
    descriptionAr: "موافقة جراحية شاملة تشمل المخاطر والتدخلات أثناء العملية.",
    sortOrder: 2,
  },
  {
    code: "ANESTHESIA",
    nameEn: "Anesthesia Consent",
    nameAr: "موافقة التخدير",
    descriptionEn: "Explains anesthesia modalities and associated risks.",
    descriptionAr: "توضح أنواع التخدير ومضاعفاته المحتملة.",
    sortOrder: 3,
  },
  {
    code: "BLOOD_TRANSFUSION",
    nameEn: "Blood Transfusion Consent",
    nameAr: "موافقة نقل الدم",
    descriptionEn: "Consent for blood and blood product transfusion with risks and alternatives.",
    descriptionAr: "موافقة لنقل الدم ومشتقاته مع بيان المخاطر والبدائل.",
    sortOrder: 4,
  },
  {
    code: "HIGH_RISK",
    nameEn: "High-Risk Procedure Consent",
    nameAr: "موافقة الإجراءات عالية الخطورة",
    descriptionEn: "Consent for high-risk interventions with medical necessity rationale.",
    descriptionAr: "موافقة للتدخلات عالية الخطورة مع تبرير ضرورتها الطبية.",
    sortOrder: 5,
  },
  {
    code: "SEDATION",
    nameEn: "Procedural Sedation Consent",
    nameAr: "موافقة التهدئة الإجرائية",
    descriptionEn: "Defines sedation safeguards before, during, and after the procedure.",
    descriptionAr: "تحدد ضوابط التهدئة قبل وأثناء وبعد الإجراء.",
    sortOrder: 6,
  },
  {
    code: "DAMA",
    nameEn: "Discharge Against Medical Advice",
    nameAr: "خروج ضد النصيحة الطبية",
    descriptionEn: "Documents DAMA decision and its legal/medical consequences.",
    descriptionAr: "يوثق قرار الخروج ضد النصيحة الطبية وآثاره القانونية والطبية.",
    sortOrder: 7,
  },
  {
    code: "RADIOLOGY_CONTRAST",
    nameEn: "Radiology / Contrast Consent",
    nameAr: "موافقة الأشعة والصبغة",
    descriptionEn: "Consent for imaging studies involving contrast or radiation exposure.",
    descriptionAr: "موافقة للفحوصات التصويرية التي تشمل الصبغة أو التعرض للإشعاع.",
    sortOrder: 8,
  },
  {
    code: "TELEMEDICINE",
    nameEn: "Telemedicine Consent",
    nameAr: "موافقة الطب عن بُعد",
    descriptionEn: "Consent for remote consultation, limitations, privacy, and documentation.",
    descriptionAr: "موافقة للاستشارة الطبية عن بُعد مع بيان القيود والخصوصية والتوثيق.",
    sortOrder: 9,
  },
  {
    code: "MEDIA",
    nameEn: "Photography / Media Consent",
    nameAr: "موافقة التصوير والإعلام",
    descriptionEn: "Consent for clinical photography, education, and media use.",
    descriptionAr: "موافقة للتصوير السريري والاستخدام التعليمي والإعلامي.",
    sortOrder: 10,
  },
];

export const CONSENT_TEMPLATES_V2: ConsentTemplateV2[] = [
  {
    id: "V2-TPL-001",
    templateCode: "GENERAL_TREATMENT_CONSENT",
    titleEn: "General Treatment Consent",
    titleAr: "الموافقة العامة للعلاج والخدمات الطبية",
    categoryCode: "GENERAL_TREATMENT",
    consentType: "GENERAL_CONSENT",
    specialty: "GENERAL_MEDICINE",
    department: "General Medicine",
    riskLevel: "MEDIUM",
    status: "IMC_APPROVED",
    version: "v3.2",
    summaryEn: "Routine examination, assessment, labs, non-invasive imaging, and general medical care.",
    summaryAr: "الفحص والتقييم والمختبر والأشعة غير التداخلية والرعاية الطبية العامة.",
    requiresWitness: false,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
  },
  {
    id: "V2-TPL-002",
    templateCode: "SURGICAL_PROCEDURE_CONSENT",
    titleEn: "Surgical Procedure Consent",
    titleAr: "موافقة العمليات الجراحية",
    categoryCode: "SURGICAL",
    consentType: "SURGERY_CONSENT",
    specialty: "GENERAL_SURGERY",
    department: "General Surgery",
    riskLevel: "HIGH",
    status: "IMC_APPROVED",
    version: "v4.1",
    summaryEn: "Open, laparoscopic, or endoscopic surgery with contingency authorization.",
    summaryAr: "الجراحة المفتوحة أو المنظارية مع تفويض للتدخل الطارئ أثناء العملية.",
    requiresWitness: true,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
  },
  {
    id: "V2-TPL-003",
    templateCode: "ORTHOPEDIC_SURGERY_CONSENT",
    titleEn: "Orthopedic Surgery Consent",
    titleAr: "موافقة جراحة العظام",
    categoryCode: "SURGICAL",
    consentType: "SURGERY_CONSENT",
    specialty: "ORTHOPEDICS",
    department: "Orthopedic Surgery",
    riskLevel: "HIGH",
    status: "IMC_APPROVED",
    version: "v2.8",
    summaryEn: "Joint, fracture, spine, or soft-tissue orthopedic procedures.",
    summaryAr: "إجراءات المفاصل والكسور والعمود الفقري والأنسجة الرخوة العظمية.",
    requiresWitness: true,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
  },
  {
    id: "V2-TPL-004",
    templateCode: "CARDIAC_SURGERY_CONSENT",
    titleEn: "Cardiac Surgery Consent",
    titleAr: "موافقة جراحة القلب",
    categoryCode: "SURGICAL",
    consentType: "SURGERY_CONSENT",
    specialty: "CARDIOTHORACIC_SURGERY",
    department: "Cardiac Surgery",
    riskLevel: "CRITICAL",
    status: "IMC_APPROVED",
    version: "v3.5",
    summaryEn: "CABG, valve repair/replacement, and other major cardiac procedures.",
    summaryAr: "تحويل مسار الشريان التاجي وإصلاح/استبدال الصمام وجراحات القلب الكبرى.",
    requiresWitness: true,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
  },
  {
    id: "V2-TPL-005",
    templateCode: "ANESTHESIA_CONSENT",
    titleEn: "Anesthesia Consent",
    titleAr: "موافقة التخدير",
    categoryCode: "ANESTHESIA",
    consentType: "ANESTHESIA_CONSENT",
    specialty: "ANESTHESIOLOGY",
    department: "Anesthesia",
    riskLevel: "HIGH",
    status: "IMC_APPROVED",
    version: "v3.0",
    summaryEn: "General, regional, local, and sedation anesthesia risks.",
    summaryAr: "مخاطر التخدير العام والنصفي والموضعي والتهدئة.",
    requiresWitness: true,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
  },
  {
    id: "V2-TPL-006",
    templateCode: "BLOOD_TRANSFUSION_CONSENT",
    titleEn: "Blood and Blood Products Transfusion Consent",
    titleAr: "موافقة نقل الدم ومشتقاته",
    categoryCode: "BLOOD_TRANSFUSION",
    consentType: "BLOOD_TRANSFUSION_CONSENT",
    specialty: "HEMATOLOGY",
    department: "Hematology",
    riskLevel: "HIGH",
    status: "IMC_APPROVED",
    version: "v2.9",
    summaryEn: "Risks, alternatives, and refusal consequences of blood transfusion.",
    summaryAr: "مخاطر وبدائل وعواقب رفض نقل الدم.",
    requiresWitness: true,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
  },
  {
    id: "V2-TPL-007",
    templateCode: "HIGH_RISK_MEDICAL_PROCEDURE_CONSENT",
    titleEn: "High-Risk Medical Procedure Consent",
    titleAr: "موافقة الإجراءات الطبية عالية الخطورة",
    categoryCode: "HIGH_RISK",
    consentType: "HIGH_RISK_PROCEDURE_CONSENT",
    specialty: "CRITICAL_CARE",
    department: "Critical Care",
    riskLevel: "CRITICAL",
    status: "PILOT_READY",
    version: "v1.5",
    summaryEn: "High-risk interventions requiring documented medical necessity.",
    summaryAr: "تدخلات عالية الخطورة تتطلب توثيق الضرورة الطبية.",
    requiresWitness: true,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
  },
  {
    id: "V2-TPL-008",
    templateCode: "PROCEDURAL_SEDATION_CONSENT",
    titleEn: "Procedural Sedation Consent",
    titleAr: "موافقة التهدئة والتسكين الإجرائي",
    categoryCode: "SEDATION",
    consentType: "SEDATION_CONSENT",
    specialty: "ANESTHESIOLOGY",
    department: "Anesthesia",
    riskLevel: "HIGH",
    status: "IMC_APPROVED",
    version: "v2.7",
    summaryEn: "Sedation safeguards before, during, and after procedures.",
    summaryAr: "ضوابط التهدئة قبل وأثناء وبعد الإجراءات.",
    requiresWitness: false,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
  },
  {
    id: "V2-TPL-009",
    templateCode: "DAMA_DISCHARGE_AGAINST_MEDICAL_ADVICE",
    titleEn: "Discharge Against Medical Advice",
    titleAr: "إقرار الخروج ضد النصيحة الطبية",
    categoryCode: "DAMA",
    consentType: "DAMA_REFUSAL_OF_DISCHARGE",
    specialty: "EMERGENCY_MEDICINE",
    department: "Emergency",
    riskLevel: "CRITICAL",
    status: "IMC_APPROVED",
    version: "v3.3",
    summaryEn: "Documents patient refusal of recommended admission or treatment.",
    summaryAr: "يوثق رفض المريض للإدخال أو العلاج الموصى به.",
    requiresWitness: true,
    requiresGuardian: false,
    requiresInterpreter: true,
    requiresSeparateConsent: true,
  },
  {
    id: "V2-TPL-010",
    templateCode: "CT_CONTRAST_CONSENT",
    titleEn: "CT with IV Contrast Consent",
    titleAr: "موافقة الأشعة المقطعية بالصبغة الوريدية",
    categoryCode: "RADIOLOGY_CONTRAST",
    consentType: "DIAGNOSTIC_IMAGING_CONSENT",
    specialty: "RADIOLOGY",
    department: "Radiology",
    riskLevel: "MEDIUM",
    status: "IMC_APPROVED",
    version: "v2.4",
    summaryEn: "Iodinated contrast risks including allergy and nephropathy.",
    summaryAr: "مخاطر الصبغة اليودية بما في ذلك الحساسية والاعتلال الكلوي.",
    requiresWitness: false,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
  },
  {
    id: "V2-TPL-011",
    templateCode: "TELEMEDICINE_CONSENT",
    titleEn: "Telemedicine Consultation Consent",
    titleAr: "موافدة الاستشارة الطبية عن بُعد",
    categoryCode: "TELEMEDICINE",
    consentType: "TELEMEDICINE_CONSENT",
    specialty: "GENERAL_MEDICINE",
    department: "Telemedicine",
    riskLevel: "LOW",
    status: "PILOT_READY",
    version: "v1.2",
    summaryEn: "Remote consultation limitations, privacy, and documentation.",
    summaryAr: "قيود الاستشارة عن بُعد والخصوصية والتوثيق.",
    requiresWitness: false,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
  },
  {
    id: "V2-TPL-012",
    templateCode: "PHOTOGRAPHY_MEDIA_CONSENT",
    titleEn: "Clinical Photography and Media Consent",
    titleAr: "موافقة التصوير السريري والإعلام",
    categoryCode: "MEDIA",
    consentType: "PHOTOGRAPHY_MEDIA_CONSENT",
    specialty: "GENERAL_MEDICINE",
    department: "Medical Affairs",
    riskLevel: "LOW",
    status: "LEGAL_REVIEW",
    version: "v1.0",
    summaryEn: "Use of clinical images for care, education, and media.",
    summaryAr: "استخدام الصور السريرية للرعاية والتعليم والإعلام.",
    requiresWitness: false,
    requiresGuardian: true,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
  },
];

export const EDUCATION_ASSETS_V2: EducationAssetV2[] = [
  { id: "EDU-001", titleEn: "What to expect before surgery", titleAr: "ما يجب توقعه قبل العملية", kind: "VIDEO", durationMinutes: 4 },
  { id: "EDU-002", titleEn: "Anesthesia types explained", titleAr: "أنواع التخدير موضحة", kind: "ARTICLE", durationMinutes: 6 },
  { id: "EDU-003", titleEn: "Blood transfusion risks and alternatives", titleAr: "مخاطر نقل الدم والبدائل", kind: "PDF", durationMinutes: 8 },
  { id: "EDU-004", titleEn: "Contrast dye allergy screening", titleAr: "فحص الحساسية للصبغة الظليلة", kind: "INFOGRAPHIC", durationMinutes: 3 },
  { id: "EDU-005", titleEn: "Your rights in telemedicine", titleAr: "حقوقك في الطب عن بُعد", kind: "VIDEO", durationMinutes: 5 },
  { id: "EDU-006", titleEn: "DAMA: understanding the risks", titleAr: "الخروج ضد النصيحة: فهم المخاطر", kind: "PDF", durationMinutes: 7 },
  { id: "EDU-007", titleEn: "Sedation safety checklist", titleAr: "قائمة التحقق من سلامة التهدئة", kind: "INFOGRAPHIC", durationMinutes: 2 },
  { id: "EDU-008", titleEn: "Cardiac surgery recovery guide", titleAr: "دليل التعافي بعد جراحة القلب", kind: "VIDEO", durationMinutes: 9 },
];

export function getCategoryByCode(code: string): ConsentCategoryV2 | undefined {
  return CONSENT_CATEGORIES_V2.find((c) => c.code === code);
}

export function getTemplateById(id: string): ConsentTemplateV2 | undefined {
  return CONSENT_TEMPLATES_V2.find((t) => t.id === id);
}

export function getTemplatesByCategory(code: string): ConsentTemplateV2[] {
  return CONSENT_TEMPLATES_V2.filter((t) => t.categoryCode === code);
}

export function getSpecialties(): string[] {
  return Array.from(new Set(CONSENT_TEMPLATES_V2.map((t) => t.specialty))).sort();
}

export function getDepartments(): string[] {
  return Array.from(new Set(CONSENT_TEMPLATES_V2.map((t) => t.department))).sort();
}

export function getConsentTypes(): string[] {
  return Array.from(new Set(CONSENT_TEMPLATES_V2.map((t) => t.consentType))).sort();
}
