import type { MockPatientEncounter } from "./types";

/**
 * Mock patient encounters for the Doctor Workspace V2 prototype.
 * These are synthetic cases designed to exercise the Procedure Mapping Engine.
 */

export const MOCK_PATIENT_ENCOUNTERS: MockPatientEncounter[] = [
  {
    id: "ENC-2026-0001",
    mrn: "MRN-102345",
    patientNameEn: "Ahmad Al-Rashid",
    patientNameAr: "أحمد الرشيد",
    dateOfBirth: "1985-03-12",
    gender: "M",
    nationalId: "1085123456",
    caseNumber: "CASE-2026-18472",
    admissionDate: "2026-06-20",
    department: "Cardiac Surgery",
    physicianName: "Dr. Khalid Al-Farsi",
    physicianSpecialty: "Cardiothoracic Surgery",
    physicianLicense: "SCHS-CT-88421",
    diagnosis: "Triple-vessel coronary artery disease",
    plannedProcedure: "Coronary Artery Bypass Grafting (CABG)",
    procedureCode: "CPT-33533",
    allergies: "Penicillin",
    syncStatus: "SYNCED",
  },
  {
    id: "ENC-2026-0002",
    mrn: "MRN-102987",
    patientNameEn: "Fatima Al-Zahrani",
    patientNameAr: "فاطمة الزهراني",
    dateOfBirth: "1972-08-05",
    gender: "F",
    nationalId: "1072987654",
    caseNumber: "CASE-2026-18491",
    admissionDate: "2026-06-21",
    department: "Orthopedic Surgery",
    physicianName: "Dr. Saeed Al-Harbi",
    physicianSpecialty: "Orthopedics",
    physicianLicense: "SCHS-ORT-77123",
    diagnosis: "Severe osteoarthritis, bilateral knees",
    plannedProcedure: "Total Knee Arthroplasty",
    procedureCode: "CPT-27447",
    allergies: "NSAIDs",
    syncStatus: "SYNCED",
  },
  {
    id: "ENC-2026-0003",
    mrn: "MRN-103112",
    patientNameEn: "Omar Hamed",
    patientNameAr: "عمر حامد",
    dateOfBirth: "1990-11-21",
    gender: "M",
    nationalId: "1090112233",
    caseNumber: "CASE-2026-18503",
    admissionDate: "2026-06-22",
    department: "General Surgery",
    physicianName: "Dr. Noura Al-Qahtani",
    physicianSpecialty: "General Surgery",
    physicianLicense: "SCHS-GS-99102",
    diagnosis: "Acute appendicitis",
    plannedProcedure: "Laparoscopic Appendectomy",
    procedureCode: "CPT-44970",
    allergies: "None known",
    syncStatus: "SYNCED",
  },
  {
    id: "ENC-2026-0004",
    mrn: "MRN-103456",
    patientNameEn: "Layla Abdullah",
    patientNameAr: "ليلى عبدالله",
    dateOfBirth: "1965-04-30",
    gender: "F",
    nationalId: "1065332211",
    caseNumber: "CASE-2026-18519",
    admissionDate: "2026-06-22",
    department: "Endoscopy",
    physicianName: "Dr. Yasser Al-Omari",
    physicianSpecialty: "Gastroenterology",
    physicianLicense: "SCHS-GE-66541",
    diagnosis: "Dyspepsia with alarm symptoms",
    plannedProcedure: "Upper GI Endoscopy with Biopsy",
    procedureCode: "CPT-43239",
    allergies: "Latex",
    syncStatus: "CACHED",
  },
  {
    id: "ENC-2026-0005",
    mrn: "MRN-103789",
    patientNameEn: "Hassan Ibrahim",
    patientNameAr: "حسن إبراهيم",
    dateOfBirth: "1958-12-09",
    gender: "M",
    nationalId: "1058778899",
    caseNumber: "CASE-2026-18527",
    admissionDate: "2026-06-23",
    department: "Critical Care",
    physicianName: "Dr. Rania Al-Sharif",
    physicianSpecialty: "Critical Care",
    physicianLicense: "SCHS-CC-33210",
    diagnosis: "Septic shock requiring vasopressors",
    plannedProcedure: "Central Venous Catheter Insertion",
    procedureCode: "CPT-93503",
    allergies: "Iodine",
    syncStatus: "SYNCED",
  },
  {
    id: "ENC-2026-0006",
    mrn: "MRN-104001",
    patientNameEn: "Noor Saeed",
    patientNameAr: "نور سعيد",
    dateOfBirth: "2001-06-15",
    gender: "F",
    nationalId: "1101665544",
    caseNumber: "CASE-2026-18531",
    admissionDate: "2026-06-23",
    department: "Emergency",
    physicianName: "Dr. Fahad Al-Mutairi",
    physicianSpecialty: "Emergency Medicine",
    physicianLicense: "SCHS-EM-44882",
    diagnosis: "Asthma exacerbation",
    plannedProcedure: "Discharge Against Medical Advice",
    procedureCode: "DAMA-001",
    allergies: "Sulfa",
    syncStatus: "UAT_MOCK",
  },
];

export function getEncounterById(id: string): MockPatientEncounter | undefined {
  return MOCK_PATIENT_ENCOUNTERS.find((e) => e.id === id);
}
