from __future__ import annotations

from io import BytesIO
from pathlib import Path
from textwrap import wrap

from reportlab.lib.pagesizes import A4
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas


def _register_arabic_font() -> str:
    candidates = [
        Path("C:/Windows/Fonts/arial.ttf"),
        Path("C:/Windows/Fonts/tahoma.ttf"),
        Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"),
    ]

    for candidate in candidates:
        if candidate.exists():
            font_name = f"cover_font_{candidate.stem.lower()}"
            try:
                if font_name not in pdfmetrics.getRegisteredFontNames():
                    pdfmetrics.registerFont(TTFont(font_name, str(candidate)))
                return font_name
            except Exception:
                continue

    return "Helvetica"


def _wrap_text(text: str, width: int) -> list[str]:
    lines: list[str] = []
    for paragraph in text.splitlines():
        if not paragraph.strip():
            lines.append("")
            continue
        lines.extend(wrap(paragraph, width=width))
    return lines


def _draw_lines(
    pdf: canvas.Canvas,
    lines: list[str],
    *,
    x: float,
    y: float,
    font_name: str,
    font_size: int,
    leading: float,
) -> float:
    text_object = pdf.beginText()
    text_object.setTextOrigin(x, y)
    text_object.setFont(font_name, font_size)
    text_object.setLeading(leading)
    for line in lines:
        text_object.textLine(line)
    pdf.drawText(text_object)
    return y - (leading * len(lines))


def generate_cover_page_pdf(bundle_context: dict) -> bytes:
    font_name = _register_arabic_font()

    case_id = str(bundle_context.get("case_id", ""))
    patient_reference = str(bundle_context.get("patient_reference", ""))
    case_date = str(bundle_context.get("case_date", ""))
    generated_at = str(bundle_context.get("generated_at", ""))
    root_hash = str(bundle_context.get("root_hash", ""))
    tsa_status = str(bundle_context.get("tsa_status", "not_configured"))
    signature_status = str(bundle_context.get("signature_status", "not_configured"))
    institution_name = str(bundle_context.get("institution_name", "International Medical Center (IMC)"))
    system_name = str(bundle_context.get("system_name", "WathiqCare"))

    if tsa_status == "enabled":
        tsa_statement = "This bundle includes a trusted timestamp from an external Time Stamping Authority (RFC 3161)."
    elif tsa_status == "unavailable":
        tsa_statement = "External timestamp authority is currently unavailable; UTC internal timestamps are recorded."
    else:
        tsa_statement = "External timestamp authority is not configured; UTC internal timestamps are recorded."

    if signature_status == "enabled":
        signature_statement = "A detached digital signature has been applied to the manifest."
    elif signature_status == "unavailable":
        signature_statement = "Detached digital signature verification service is currently unavailable."
    else:
        signature_statement = "Detached digital signature is not configured in this environment."

    english_sections = [
        "EVIDENCE BUNDLE CERTIFICATE",
        "Medical Discharge Refusal Case Documentation",
        f"Institution: {institution_name}",
        f"System: {system_name} - Tamper-evident and internally verifiable clinical-legal documentation system",
        "",
        "1. Case Identification",
        f"Case ID: {case_id}",
        f"Patient Reference: {patient_reference}",
        f"Date of Case Initiation: {case_date}",
        f"Date of Bundle Generation (UTC): {generated_at}",
        "",
        "2. Integrity Statement",
        "This package is generated by a controlled tamper-evident workflow.",
        "Any post-generation modification is expected to be detectable by integrity checks.",
        f"Bundle Root Hash (SHA-256): {root_hash}",
        "",
        "3. Chain of Custody Declaration",
        "The package contains sequential and hash-linked custody records with UTC timestamps.",
        "",
        "4. Timestamping Statement",
        tsa_statement,
        "",
        "5. Signature Statement",
        signature_statement,
        "",
        "6. Legal Purpose",
        "This package documents discharge decision, refusal workflow, and auditable clinical/legal records.",
        "",
        "7. Disclaimer",
        "This package is tamper-evident and internally verifiable.",
        "External cryptographic validation may be required for judicial admissibility depending on authority requirements.",
    ]

    arabic_sections = [
        "شهادة حزمة الأدلة",
        "توثيق حالة رفض الخروج الطبي",
        f"الجهة: {institution_name}",
        f"النظام: {system_name} - نظام توثيق طبي قانوني مضاد للعبث وقابل للتحقق الداخلي",
        "",
        "1. تعريف الحالة",
        f"معرف الحالة: {case_id}",
        f"مرجع المريض: {patient_reference}",
        f"تاريخ بدء الحالة: {case_date}",
        f"تاريخ إنشاء الحزمة (UTC): {generated_at}",
        "",
        "2. بيان السلامة",
        "تم إنشاء هذه الحزمة عبر مسار تقني محكوم ومضاد للعبث.",
        "أي تعديل لاحق على المحتوى يفترض كشفه عبر فحوصات السلامة.",
        f"بصمة جذر الحزمة (SHA-256): {root_hash}",
        "",
        "3. إقرار سلسلة الحيازة",
        "تتضمن الحزمة سجلاً متسلسلاً ومرتبطاً بالتجزئة لسلسلة الحيازة مع تواريخ UTC.",
        "",
        "4. بيان الختم الزمني",
        (
            "تتضمن الحزمة ختماً زمنياً من جهة ختم زمني خارجية (RFC 3161)."
            if tsa_status == "enabled"
            else "تعتمد الحزمة حالياً على أختام زمنية داخلية بتوقيت UTC."
        ),
        "",
        "5. بيان التوقيع",
        (
            "تم إرفاق توقيع رقمي منفصل لملف manifest."
            if signature_status == "enabled"
            else "التوقيع الرقمي المنفصل غير مفعل حالياً في هذه البيئة."
        ),
        "",
        "6. الغرض القانوني",
        "تهدف الحزمة إلى توثيق قرار الخروج الطبي ومسار الرفض وسجلات المراجعة.",
        "",
        "7. إخلاء مسؤولية",
        "هذه الحزمة مضادة للعبث وقابلة للتحقق الداخلي.",
        "قد تتطلب القابلية القضائية الكاملة تحققاً خارجياً وفق متطلبات الجهات المختصة.",
    ]

    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4, pageCompression=0, invariant=1)
    pdf.setTitle("Evidence Bundle Certificate")
    pdf.setAuthor(system_name)
    pdf.setCreator(system_name)
    pdf.setSubject("Tamper-evident and internally verifiable evidence package certificate")

    width, height = A4
    margin_x = 50

    y = height - 60
    y = _draw_lines(
        pdf,
        _wrap_text("\n".join(english_sections), 98),
        x=margin_x,
        y=y,
        font_name=font_name,
        font_size=10,
        leading=14,
    )

    pdf.showPage()
    y = height - 60
    _draw_lines(
        pdf,
        _wrap_text("\n".join(arabic_sections), 92),
        x=margin_x,
        y=y,
        font_name=font_name,
        font_size=10,
        leading=14,
    )

    pdf.save()
    return buffer.getvalue()
