import type { ConsentFieldMapping } from "@/lib/consents/field-mapping/types";

export const ADENOTONSILLECTOMY_FIELD_MAPPING: ConsentFieldMapping = {
  formId: "imc-approved-adenotonsillectomy",
  slug: "adenotonsillectomy",
  titleEn: "Adenotonsillectomy",
  layoutFamily: "IMC_GENERAL_PROCEDURE_CONSENT",
  version: "0.1.0",
  verificationStatus: "DRAFT",
  requiresDoctorCompletion: true,
  supportsAnesthesiaWorkflow: false,
  blocksPatientDispatchUntilVerified: true,
  fields: [
    {
      key: "condition_and_treatment",
      section: "B",
      labelEn: "Condition and treatment",
      role: "PHYSICIAN_REQUIRED",
      type: "MULTILINE_TEXT",
      required: true,
      maxLength: 1200,
      multiline: true,
      placeholderEn: "Document the patient's condition, proposed treatment, and clinical context.",
      coordinates: {
        coordinateMode: "NORMALIZED",
        page: 1,
        x: 0.085,
        y: 0.285,
        width: 0.39,
        height: 0.03,
      },
      arabicCoordinates: {
        coordinateMode: "NORMALIZED",
        page: 1,
        x: 0.5124,
        y: 0.276,
        width: 0.39,
        height: 0.03,
      },
    },
    {
      key: "procedure_site_side",
      section: "B",
      labelEn: "Procedure, site and/or side",
      role: "PHYSICIAN_REQUIRED",
      type: "MULTILINE_TEXT",
      required: true,
      maxLength: 800,
      multiline: true,
      placeholderEn: "Document the procedure, site, side, or laterality where applicable.",
      coordinates: {
        coordinateMode: "NORMALIZED",
        page: 1,
        x: 0.085,
        y: 0.391,
        width: 0.39,
        height: 0.03,
      },
      arabicCoordinates: {
        coordinateMode: "NORMALIZED",
        page: 1,
        x: 0.5124,
        y: 0.382,
        width: 0.39,
        height: 0.03,
      },
    },
    {
      key: "significant_risks_options",
      section: "D",
      labelEn: "Significant risks and procedure options",
      role: "READ_ONLY",
      type: "MULTILINE_TEXT",
      required: false,
      maxLength: 1600,
      multiline: true,
      placeholderEn: "Document significant risks, material risks, and available options.",
    },
    {
      key: "risks_of_not_having_procedure",
      section: "E",
      labelEn: "Risks of not having this procedure",
      role: "READ_ONLY",
      type: "MULTILINE_TEXT",
      required: false,
      maxLength: 1200,
      multiline: true,
      placeholderEn: "Document risks and consequences of refusing or delaying the procedure.",
    },
    {
      key: "anesthesia_applies",
      section: "F",
      labelEn: "Anesthesia applies",
      role: "READ_ONLY",
      type: "CHECKBOX",
      required: false,
      sourcePath: "metadata.anesthesia.applies",
    },
    {
      key: "anesthetic_type_discussed",
      section: "F",
      labelEn: "Type of anesthetic discussed",
      role: "ANESTHESIA_OPTIONAL",
      type: "MULTILINE_TEXT",
      required: false,
      requiredWhen: "anesthesia_applies === true",
      maxLength: 1000,
      multiline: true,
      placeholderEn: "Document the type of anesthesia discussed and reviewed.",
    },
    {
      key: "treating_physician_signature",
      labelEn: "Treating physician signature",
      labelAr: "توقيع الطبيب المعالج",
      role: "PHYSICIAN_REQUIRED",
      type: "SIGNATURE",
      required: true,
      coordinates: {
        coordinateMode: "NORMALIZED",
        page: 2,
        x: 0.145,
        y: 0.455,
        width: 0.3,
        height: 0.055,
      },
      arabicCoordinates: {
        coordinateMode: "NORMALIZED",
        page: 2,
        x: 0.5124,
        y: 0.455,
        width: 0.3,
        height: 0.055,
      },
    },
    {
      key: "physician_name",
      labelEn: "Physician name",
      labelAr: "اسم الطبيب",
      role: "SYSTEM_AUTO",
      type: "TEXT",
      required: false,
      sourcePath: "metadata.physicianIdentity.name",
      coordinates: {
        coordinateMode: "NORMALIZED",
        page: 2,
        x: 0.145,
        y: 0.518,
        width: 0.3,
        height: 0.022,
      },
      arabicCoordinates: {
        coordinateMode: "NORMALIZED",
        page: 2,
        x: 0.5124,
        y: 0.518,
        width: 0.3,
        height: 0.022,
      },
    },
    {
      key: "physician_designation",
      labelEn: "Physician designation",
      labelAr: "تعيين الطبيب",
      role: "SYSTEM_AUTO",
      type: "TEXT",
      required: false,
      sourcePath: "metadata.physicianIdentity.specialty",
      coordinates: {
        coordinateMode: "NORMALIZED",
        page: 2,
        x: 0.145,
        y: 0.545,
        width: 0.3,
        height: 0.022,
      },
      arabicCoordinates: {
        coordinateMode: "NORMALIZED",
        page: 2,
        x: 0.5124,
        y: 0.545,
        width: 0.3,
        height: 0.022,
      },
    },
    {
      key: "physician_signed_date",
      labelEn: "Signed date",
      labelAr: "تاريخ التوقيع",
      role: "SYSTEM_AUTO",
      type: "DATE",
      required: false,
      sourcePath: "metadata.physicianSignature.signedAtDate",
      coordinates: {
        coordinateMode: "NORMALIZED",
        page: 2,
        x: 0.145,
        y: 0.572,
        width: 0.14,
        height: 0.022,
      },
      arabicCoordinates: {
        coordinateMode: "NORMALIZED",
        page: 2,
        x: 0.5124,
        y: 0.572,
        width: 0.14,
        height: 0.022,
      },
    },
    {
      key: "physician_signed_time",
      labelEn: "Signed time",
      labelAr: "وقت التوقيع",
      role: "SYSTEM_AUTO",
      type: "TEXT",
      required: false,
      sourcePath: "metadata.physicianSignature.signedAtTime",
      coordinates: {
        coordinateMode: "NORMALIZED",
        page: 2,
        x: 0.305,
        y: 0.572,
        width: 0.14,
        height: 0.022,
      },
      arabicCoordinates: {
        coordinateMode: "NORMALIZED",
        page: 2,
        x: 0.6724,
        y: 0.572,
        width: 0.14,
        height: 0.022,
      },
    },
    {
      key: "patient_signature",
      labelEn: "Patient signature",
      labelAr: "توقيع المريض",
      role: "PATIENT_REQUIRED",
      type: "SIGNATURE",
      required: true,
      coordinates: {
        coordinateMode: "NORMALIZED",
        page: 1,
        x: 0.145,
        y: 0.884,
        width: 0.3,
        height: 0.026,
      },
    },
    {
      key: "guardian_signature",
      labelEn: "Substitute decision maker signature",
      role: "READ_ONLY",
      type: "SIGNATURE",
      required: false,
      coordinates: {
        coordinateMode: "NORMALIZED",
        page: 2,
        x: 0.145,
        y: 0.236,
        width: 0.3,
        height: 0.026,
      },
    },
    {
      key: "signed_at",
      labelEn: "Signed date and time",
      role: "SYSTEM_AUTO",
      type: "DATETIME",
      required: true,
    },
  ],
};
