import type { ConsentFieldMapping } from "@/lib/consents/field-mapping/types";

export const ADENOTONSILLECTOMY_FIELD_MAPPING: ConsentFieldMapping = {
  formId: "imc-approved-adenotonsillectomy",
  slug: "adenotonsillectomy",
  titleEn: "Adenotonsillectomy",
  layoutFamily: "IMC_GENERAL_PROCEDURE_CONSENT",
  version: "0.1.0",
  verificationStatus: "DRAFT",
  requiresDoctorCompletion: true,
  supportsAnesthesiaWorkflow: false,
  blocksPatientDispatchUntilVerified: true,
  coordinateMode: "NORMALIZED",
  fields: [
    {
      key: "condition_and_treatment",
      section: "B",
      labelEn: "Condition and treatment",
      role: "PHYSICIAN_REQUIRED",
      type: "MULTILINE_TEXT",
      required: true,
      maxLength: 1200,
      multiline: true,
      placeholderEn: "Document the patient's condition, proposed treatment, and clinical context.",
      coordinates: {
        page: 1,
        x: 0.085,
        y: 0.285,
        size: 8,
        maxWidth: 0.39,
      },
    },
    {
      key: "procedure_site_side",
      section: "B",
      labelEn: "Procedure, site and/or side",
      role: "PHYSICIAN_REQUIRED",
      type: "MULTILINE_TEXT",
      required: true,
      maxLength: 800,
      multiline: true,
      placeholderEn: "Document the procedure, site, side, or laterality where applicable.",
      coordinates: {
        page: 1,
        x: 0.085,
        y: 0.391,
        size: 8,
        maxWidth: 0.39,
      },
    },
    {
      key: "significant_risks_options",
      section: "D",
      labelEn: "Significant risks and procedure options",
      role: "READ_ONLY",
      type: "MULTILINE_TEXT",
      required: false,
      maxLength: 1600,
      multiline: true,
      placeholderEn: "Document significant risks, material risks, and available options.",
    },
    {
      key: "risks_of_not_having_procedure",
      section: "E",
      labelEn: "Risks of not having this procedure",
      role: "READ_ONLY",
      type: "MULTILINE_TEXT",
      required: false,
      maxLength: 1200,
      multiline: true,
      placeholderEn: "Document risks and consequences of refusing or delaying the procedure.",
    },
    {
      key: "anesthesia_applies",
      section: "F",
      labelEn: "Anesthesia applies",
      role: "READ_ONLY",
      type: "CHECKBOX",
      required: false,
      sourcePath: "metadata.anesthesia.applies",
    },
    {
      key: "anesthetic_type_discussed",
      section: "F",
      labelEn: "Type of anesthetic discussed",
      role: "ANESTHESIA_OPTIONAL",
      type: "MULTILINE_TEXT",
      required: false,
      requiredWhen: "anesthesia_applies === true",
      maxLength: 1000,
      multiline: true,
      placeholderEn: "Document the type of anesthesia discussed and reviewed.",
    },
    {
      key: "treating_physician_signature",
      labelEn: "Treating physician signature",
      role: "PHYSICIAN_REQUIRED",
      type: "SIGNATURE",
      required: true,
      coordinates: {
        page: 2,
        x: 0.145,
        y: 0.468,
        size: 8,
        maxWidth: 0.3,
      },
    },
    {
      key: "patient_signature",
      labelEn: "Patient / guardian signature",
      role: "PATIENT_REQUIRED",
      type: "SIGNATURE",
      required: true,
    },
    {
      key: "signed_at",
      labelEn: "Signed date and time",
      role: "SYSTEM_AUTO",
      type: "DATETIME",
      required: true,
    },
  ],
};
