import type { ConsentFieldMapping } from "@/lib/consents/field-mapping/types";

/**
 * IMC MR 1135 Amputation consent field mapping.
 *
 * This mapping drives physician-journey readiness and draft-overlay fallback.
 * The field-addressed renderer uses the verified AcroForm manifest directly for
 * precise widget placement on the canonical approved PDF.
 */

export const AMPUTATION_FIELD_MAPPING: ConsentFieldMapping = {
  formId: "imc-approved-amputation",
  slug: "amputation",
  titleEn: "Amputation",
  layoutFamily: "IMC_MR_1135_ACROFORM",
  version: "2026.07.15",
  verificationStatus: "VERIFIED",
  requiresDoctorCompletion: true,
  supportsAnesthesiaWorkflow: true,
  blocksPatientDispatchUntilVerified: true,
  fields: [
    {
      key: "patient_name",
      labelEn: "Patient name",
      labelAr: "اسم المريض",
      role: "SYSTEM_AUTO",
      type: "TEXT",
      required: false,
      sourcePath: "metadata.patient.name",
    },
    {
      key: "mrn",
      labelEn: "Medical record number",
      labelAr: "رقم الملف الطبي",
      role: "SYSTEM_AUTO",
      type: "TEXT",
      required: false,
      sourcePath: "metadata.patient.mrn",
    },
    {
      key: "date_of_birth",
      labelEn: "Date of birth",
      labelAr: "تاريخ الميلاد",
      role: "SYSTEM_AUTO",
      type: "DATE",
      required: false,
      sourcePath: "metadata.patient.dateOfBirth",
    },
    {
      key: "interpreter_required",
      section: "A",
      labelEn: "Interpreter required",
      labelAr: "هل يحتاج المريض مترجم",
      role: "INTERPRETER_CONDITIONAL",
      type: "CHECKBOX",
      required: false,
    },
    {
      key: "interpreter_present",
      section: "A",
      labelEn: "Interpreter present",
      labelAr: "هل حضر المترجم",
      role: "INTERPRETER_CONDITIONAL",
      type: "CHECKBOX",
      required: false,
    },
    {
      key: "condition_description_en",
      section: "B",
      labelEn: "Condition in patient's own words",
      labelAr: "وصف الحالة المرضية بكلمات المريض",
      role: "PHYSICIAN_REQUIRED",
      type: "MULTILINE_TEXT",
      required: true,
      maxLength: 1200,
      multiline: true,
      placeholderEn: "Document the patient's condition, indication, and clinical context in English.",
    },
    {
      key: "condition_description_ar",
      section: "B",
      labelEn: "Condition in patient's own words (Arabic)",
      labelAr: "وصف الحالة المرضية بكلمات المريض (عربي)",
      role: "PHYSICIAN_REQUIRED",
      type: "MULTILINE_TEXT",
      required: true,
      maxLength: 1200,
      multiline: true,
      placeholderAr: "وثّق نفس الحالة بالعربية.",
    },
    {
      key: "proposed_procedure_en",
      section: "C",
      labelEn: "Proposed procedure, site and side",
      labelAr: "الإجراء المقترح مع الموضع والجهة",
      role: "PHYSICIAN_REQUIRED",
      type: "MULTILINE_TEXT",
      required: true,
      maxLength: 1000,
      multiline: true,
      placeholderEn: "Document the proposed procedure, anatomical site, and laterality in English.",
    },
    {
      key: "proposed_procedure_ar",
      section: "C",
      labelEn: "Proposed procedure, site and side (Arabic)",
      labelAr: "الإجراء المقترح مع الموضع والجهة (عربي)",
      role: "PHYSICIAN_REQUIRED",
      type: "MULTILINE_TEXT",
      required: true,
      maxLength: 1000,
      multiline: true,
      placeholderAr: "وثّق نفس الإجراء بالعربية.",
    },
    {
      key: "significant_risks_options_en",
      section: "D",
      labelEn: "Significant risks and procedure options",
      labelAr: "المخاطر الهامة وخيارات الإجراء",
      role: "PHYSICIAN_REQUIRED",
      type: "MULTILINE_TEXT",
      required: true,
      maxLength: 1600,
      multiline: true,
      placeholderEn: "Document material risks, benefits, and alternatives discussed in English.",
    },
    {
      key: "significant_risks_options_ar",
      section: "D",
      labelEn: "Significant risks and procedure options (Arabic)",
      labelAr: "المخاطر الهامة وخيارات الإجراء (عربي)",
      role: "PHYSICIAN_REQUIRED",
      type: "MULTILINE_TEXT",
      required: true,
      maxLength: 1600,
      multiline: true,
      placeholderAr: "وثّق نفس المخاطر والخيارات بالعربية.",
    },
    {
      key: "significant_risks_options_cont_en",
      section: "D (cont.)",
      labelEn: "Significant risks/options continuation",
      labelAr: "تكملة المخاطر الهامة وخيارات الإجراء",
      role: "PHYSICIAN_REQUIRED",
      type: "MULTILINE_TEXT",
      required: true,
      maxLength: 1600,
      multiline: true,
      placeholderEn: "Continue risks and options in English.",
    },
    {
      key: "significant_risks_options_cont_ar",
      section: "D (cont.)",
      labelEn: "Significant risks/options continuation (Arabic)",
      labelAr: "تكملة المخاطر الهامة وخيارات الإجراء (عربي)",
      role: "PHYSICIAN_REQUIRED",
      type: "MULTILINE_TEXT",
      required: true,
      maxLength: 1600,
      multiline: true,
      placeholderAr: "استكمل المخاطر والخيارات بالعربية.",
    },
    {
      key: "risks_without_procedure_en",
      section: "E",
      labelEn: "Risks of not having the procedure",
      labelAr: "مخاطر عدم الخضوع للإجراء",
      role: "PHYSICIAN_REQUIRED",
      type: "MULTILINE_TEXT",
      required: true,
      maxLength: 1600,
      multiline: true,
      placeholderEn: "Document risks of refusal or delay in English.",
    },
    {
      key: "risks_without_procedure_ar",
      section: "E",
      labelEn: "Risks of not having the procedure (Arabic)",
      labelAr: "مخاطر عدم الخضوع للإجراء (عربي)",
      role: "PHYSICIAN_REQUIRED",
      type: "MULTILINE_TEXT",
      required: true,
      maxLength: 1600,
      multiline: true,
      placeholderAr: "وثّق نفس المخاطر بالعربية.",
    },
    {
      key: "anaesthetic_discussed_en",
      section: "F",
      labelEn: "Type of anaesthetic discussed",
      labelAr: "نوع التخدير الذي تمت مناقشته",
      role: "ANESTHESIA_REQUIRED",
      type: "MULTILINE_TEXT",
      required: true,
      requiredWhen: "anesthesia_applies === true",
      maxLength: 1200,
      multiline: true,
      placeholderEn: "Document the type of anaesthetic discussed in English.",
    },
    {
      key: "anaesthetic_discussed_ar",
      section: "F",
      labelEn: "Type of anaesthetic discussed (Arabic)",
      labelAr: "نوع التخدير الذي تمت مناقشته (عربي)",
      role: "ANESTHESIA_REQUIRED",
      type: "MULTILINE_TEXT",
      required: true,
      requiredWhen: "anesthesia_applies === true",
      maxLength: 1200,
      multiline: true,
      placeholderAr: "وثّق نفس مناقشة التخدير بالعربية.",
    },
    {
      key: "education_anaesthetic_sheet_provided",
      section: "G",
      labelEn: "Anaesthetic information sheet provided",
      labelAr: "تم تسليم ورقة معلومات التخدير",
      role: "READ_ONLY",
      type: "CHECKBOX",
      required: false,
    },
    {
      key: "education_epidural_spinal_sheet_provided",
      section: "G",
      labelEn: "Epidural and spinal information sheet provided",
      labelAr: "تم تسليم ورقة التخدير النصفي",
      role: "READ_ONLY",
      type: "CHECKBOX",
      required: false,
    },
    {
      key: "education_amputation_sheet_provided",
      section: "G",
      labelEn: "Amputation information sheet provided",
      labelAr: "تم تسليم ورقة معلومات البتر",
      role: "READ_ONLY",
      type: "CHECKBOX",
      required: false,
    },
    {
      key: "consent_patient_name",
      labelEn: "Patient consent name",
      labelAr: "اسم المريض في الإقرار",
      role: "PATIENT_REQUIRED",
      type: "TEXT",
      required: true,
      sourcePath: "metadata.patient.name",
    },
    {
      key: "patient_signature",
      labelEn: "Patient signature",
      labelAr: "توقيع المريض",
      role: "PATIENT_REQUIRED",
      type: "SIGNATURE",
      required: true,
    },
    {
      key: "consent_date",
      labelEn: "Consent date",
      labelAr: "تاريخ الإقرار",
      role: "SYSTEM_AUTO",
      type: "DATE",
      required: true,
      sourcePath: "metadata.patientSignature.signedAtDate",
    },
    {
      key: "consent_time",
      labelEn: "Consent time",
      labelAr: "وقت الإقرار",
      role: "SYSTEM_AUTO",
      type: "DATETIME",
      required: true,
      sourcePath: "metadata.patientSignature.signedAtTime",
    },
    {
      key: "substitute_name",
      labelEn: "Substitute decision-maker name",
      labelAr: "اسم من ينوب عن المريض",
      role: "GUARDIAN_CONDITIONAL",
      type: "TEXT",
      required: false,
    },
    {
      key: "substitute_signature",
      labelEn: "Substitute decision-maker signature",
      labelAr: "توقيع من ينوب عن المريض",
      role: "GUARDIAN_CONDITIONAL",
      type: "SIGNATURE",
      required: false,
    },
    {
      key: "substitute_relationship",
      labelEn: "Relationship to patient",
      labelAr: "صلة من ينوب عن المريض بالمريض",
      role: "GUARDIAN_CONDITIONAL",
      type: "TEXT",
      required: false,
    },
    {
      key: "substitute_date",
      labelEn: "Substitute consent date",
      labelAr: "تاريخ إقرار من ينوب عن المريض",
      role: "GUARDIAN_CONDITIONAL",
      type: "DATE",
      required: false,
    },
    {
      key: "substitute_time",
      labelEn: "Substitute consent time",
      labelAr: "وقت إقرار من ينوب عن المريض",
      role: "GUARDIAN_CONDITIONAL",
      type: "DATETIME",
      required: false,
    },
    {
      key: "substitute_contact",
      labelEn: "Substitute contact number",
      labelAr: "رقم اتصال من ينوب عن المريض",
      role: "GUARDIAN_CONDITIONAL",
      type: "TEXT",
      required: false,
    },
    {
      key: "physician_name",
      labelEn: "Doctor or delegate name",
      labelAr: "اسم الطبيب أو المندوب",
      role: "PHYSICIAN_REQUIRED",
      type: "TEXT",
      required: true,
      sourcePath: "metadata.physicianIdentity.name",
    },
    {
      key: "physician_designation",
      labelEn: "Doctor/delegate designation",
      labelAr: "طبيعة إنابة الطبيب أو المندوب",
      role: "PHYSICIAN_REQUIRED",
      type: "TEXT",
      required: true,
      sourcePath: "metadata.physicianIdentity.specialty",
    },
    {
      key: "physician_signature",
      labelEn: "Doctor/delegate signature",
      labelAr: "توقيع الطبيب أو المندوب",
      role: "PHYSICIAN_REQUIRED",
      type: "SIGNATURE",
      required: true,
    },
    {
      key: "physician_signed_date",
      labelEn: "Doctor/delegate date",
      labelAr: "تاريخ الطبيب أو المندوب",
      role: "SYSTEM_AUTO",
      type: "DATE",
      required: true,
      sourcePath: "metadata.physicianSignature.signedAtDate",
    },
    {
      key: "physician_signed_time",
      labelEn: "Doctor/delegate time",
      labelAr: "وقت الطبيب أو المندوب",
      role: "SYSTEM_AUTO",
      type: "DATETIME",
      required: true,
      sourcePath: "metadata.physicianSignature.signedAtTime",
    },
    ...[1, 2].flatMap((n) => [
      {
        key: `witness${n}_name`,
        labelEn: `Witness ${n} name`,
        labelAr: `اسم الشاهد ${n === 1 ? "الأول" : "الثاني"}`,
        role: "WITNESS_CONDITIONAL" as const,
        type: "TEXT" as const,
        required: false,
      },
      {
        key: `witness${n}_signature`,
        labelEn: `Witness ${n} signature`,
        labelAr: `توقيع الشاهد ${n === 1 ? "الأول" : "الثاني"}`,
        role: "WITNESS_CONDITIONAL" as const,
        type: "SIGNATURE" as const,
        required: false,
      },
      {
        key: `witness${n}_date`,
        labelEn: `Witness ${n} date`,
        labelAr: `تاريخ الشاهد ${n === 1 ? "الأول" : "الثاني"}`,
        role: "WITNESS_CONDITIONAL" as const,
        type: "DATE" as const,
        required: false,
      },
      {
        key: `witness${n}_time`,
        labelEn: `Witness ${n} time`,
        labelAr: `وقت الشاهد ${n === 1 ? "الأول" : "الثاني"}`,
        role: "WITNESS_CONDITIONAL" as const,
        type: "DATETIME" as const,
        required: false,
      },
    ]),
  ],
};
