export const WATHIQCARE_PDF_BRANDING = {
  productName: "WathiqCare™",
  enterpriseSubtitle: "Enterprise Healthcare Legal Automation Platform",
  secondaryDescription: "Healthcare Legal Automation & Consent Governance",
  footerText: "WathiqCare™ Enterprise Healthcare Legal Automation Platform",
  rightsText: "© 2026 International Medical Center (IMC). All rights reserved.",
  crNumber: "CR: 4030143596",
  documentFooter:
    "This document was generated by WathiqCare™ as part of the healthcare legal evidence workflow.",
  letterheadTitle: "International Medical Center (IMC)",
  letterheadSubtitle: "Official Medico-Legal Evidence Document",
} as const;

export function buildStandardFooterLines(): string[] {
  return [
    WATHIQCARE_PDF_BRANDING.footerText,
    WATHIQCARE_PDF_BRANDING.rightsText,
    WATHIQCARE_PDF_BRANDING.crNumber,
  ];
}

export function resolveLegalFooterText(customText?: string | null): string {
  return customText?.trim() || WATHIQCARE_PDF_BRANDING.documentFooter;
}