import { ConsentSectionKind } from "@/lib/server/prisma-enums";
import { AR_CONSENT_TEXT } from "@/lib/server/consent.ar";
import { EN_CONSENT_TEXT } from "@/lib/server/consent.en";

export type SaudiEnterpriseTemplateSeed = {
  categoryCode: string;
  categoryNameAr: string;
  categoryNameEn: string;
  templateCode: string;
  consentType: string;
  specialty: string;
  department: string;
  titleAr: string;
  titleEn: string;
  summaryAr: string;
  summaryEn: string;
  riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  requiresWitness: boolean;
  requiresGuardian: boolean;
  requiresInterpreter: boolean;
  requiresSeparateConsent: boolean;
  specificAr: string;
  specificEn: string;
};

type SectionSeed = {
  sectionKey: string;
  sectionKind: ConsentSectionKind;
  titleAr: string;
  titleEn: string;
  contentAr: string;
  contentEn: string;
  isRequired: boolean;
  isEditableByPhysician: boolean;
  sortOrder: number;
};

const {
  AR_INTRO,
  AR_INTRO_2,
  AR_PDPL,
  AR_VOLUNTARY,
  AR_NO_GUARANTEE,
  AR_STANDARD_BENEFITS,
  AR_STANDARD_RISKS,
  AR_STANDARD_SERIOUS,
  AR_STANDARD_ALTERNATIVES,
  AR_STANDARD_REFUSAL,
} = AR_CONSENT_TEXT;

const {
  EN_INTRO,
  EN_INTRO_2,
  EN_PDPL,
  EN_VOLUNTARY,
  EN_NO_GUARANTEE,
  EN_STANDARD_BENEFITS,
  EN_STANDARD_RISKS,
  EN_STANDARD_SERIOUS,
  EN_STANDARD_ALTERNATIVES,
  EN_STANDARD_REFUSAL,
} = EN_CONSENT_TEXT;

export const SAUDI_ENTERPRISE_TEMPLATES: SaudiEnterpriseTemplateSeed[] = [
  {
    categoryCode: "GENERAL_TREATMENT",
    categoryNameAr: "الموافقة العامة",
    categoryNameEn: "General Consent",
    templateCode: "GENERAL_TREATMENT_CONSENT",
    consentType: "GENERAL_CONSENT",
    specialty: "GENERAL_MEDICINE",
    department: "GENERAL_MEDICINE",
    titleAr: "الموافقة العامة للعلاج والخدمات الطبية",
    titleEn: "General Treatment Consent",
    summaryAr: "تغطي الفحص والتقييم والعلاج الروتيني والخدمات الطبية العامة.",
    summaryEn: "Covers clinical assessment, routine treatment, and general medical services.",
    riskLevel: "MEDIUM",
    requiresWitness: false,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
    specificAr: "يشمل هذا الإذن الخدمات الطبية العامة، الفحص السريري، التقييم الطبي، الفحوصات المخبرية، الأشعة غير التداخلية، إعطاء الأدوية المعتادة، الرعاية التمريضية، المتابعة الطبية، وإجراءات الاستقرار الطبي الطارئة التي لا تتطلب موافقة خاصة مستقلة.",
    specificEn: "This consent covers general medical services, clinical examination, medical assessment, laboratory tests, non-invasive radiology, routine medication administration, nursing care, medical follow-up, and emergency stabilization measures that do not require separate specific consent.",
  },
  {
    categoryCode: "SURGICAL",
    categoryNameAr: "موافقة جراحية",
    categoryNameEn: "Surgical Consent",
    templateCode: "SURGICAL_PROCEDURE_CONSENT",
    consentType: "SURGERY_CONSENT",
    specialty: "SURGERY",
    department: "GENERAL_SURGERY",
    titleAr: "موافقة العمليات الجراحية",
    titleEn: "Surgical Procedure Consent",
    summaryAr: "موافقة شاملة للعمليات الجراحية ومخاطرها والتدخلات غير المتوقعة.",
    summaryEn: "Comprehensive surgical consent including risks and intraoperative contingencies.",
    riskLevel: "HIGH",
    requiresWitness: true,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
    specificAr: "أفهم أن العملية الجراحية قد تتطلب فتحاً جراحياً أو تدخلاً بالمنظار أو استخدام أدوات طبية، وقد يترتب عليها نزيف، عدوى، جلطات، إصابة أعصاب أو أوعية دموية، ألم، ندبات، فشل الإجراء، الحاجة إلى عملية إضافية، نقل دم، عناية مركزة، عجز دائم أو وفاة لا قدر الله. وأفوض الفريق الجراحي باتخاذ ما يلزم طبياً أثناء العملية إذا ظهرت حالة غير متوقعة تستدعي التدخل الفوري لحماية حياتي أو سلامتي.",
    specificEn: "I understand that the surgical procedure may involve open surgery, endoscopic intervention, or use of medical instruments, and may result in bleeding, infection, clots, nerve or vascular injury, pain, scarring, failure of the procedure, need for additional surgery, blood transfusion, ICU admission, permanent disability, or death. I authorize the surgical team to take medically necessary action during the procedure if unforeseen findings require immediate intervention to protect my life or health.",
  },
  {
    categoryCode: "ANESTHESIA",
    categoryNameAr: "موافقة التخدير",
    categoryNameEn: "Anesthesia Consent",
    templateCode: "ANESTHESIA_CONSENT",
    consentType: "ANESTHESIA_CONSENT",
    specialty: "ANESTHESIA",
    department: "ANESTHESIA",
    titleAr: "موافقة التخدير",
    titleEn: "Anesthesia Consent",
    summaryAr: "توضح أنواع التخدير ومضاعفاته المحتملة.",
    summaryEn: "Explains anesthesia modalities and associated risks.",
    riskLevel: "HIGH",
    requiresWitness: true,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
    specificAr: "يشمل هذا الإذن التخدير العام أو النصفي أو الموضعي أو التهدئة الإجرائية بحسب ما يراه طبيب التخدير مناسباً. وقد تشمل المخاطر اضطرابات التنفس، انخفاض الضغط، اضطراب القلب، الحساسية، القيء، إصابة الأسنان أو الحلق، تلف الأعصاب، الحاجة للتنفس الصناعي أو العناية المركزة، ومضاعفات نادرة قد تصل إلى الوفاة.",
    specificEn: "This consent covers general, regional, local anesthesia, or procedural sedation as deemed appropriate by the anesthesiologist. Risks may include respiratory complications, low blood pressure, cardiac disturbance, allergic reaction, vomiting, dental or throat injury, nerve injury, need for mechanical ventilation or ICU admission, and rare complications including death.",
  },
  {
    categoryCode: "BLOOD_TRANSFUSION",
    categoryNameAr: "موافقة نقل الدم",
    categoryNameEn: "Blood Transfusion Consent",
    templateCode: "BLOOD_AND_PRODUCTS_TRANSFUSION_CONSENT",
    consentType: "BLOOD_TRANSFUSION_CONSENT",
    specialty: "GENERAL_MEDICINE",
    department: "HEMATOLOGY",
    titleAr: "موافقة نقل الدم ومشتقاته",
    titleEn: "Blood and Blood Products Transfusion Consent",
    summaryAr: "موافقة لنقل الدم ومشتقاته مع بيان المخاطر والبدائل.",
    summaryEn: "Consent for blood and blood product transfusion with risks and alternatives.",
    riskLevel: "HIGH",
    requiresWitness: true,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
    specificAr: "أفهم أن نقل الدم أو مشتقاته قد يكون ضرورياً لعلاج النزيف أو فقر الدم أو الحالات الحرجة. وقد تشمل المخاطر الحساسية، الحمى، تفاعل نقل الدم، اضطرابات المناعة، زيادة السوائل، ومخاطر العدوى رغم إجراءات الفحص والتحقق المعتمدة. وأفهم أن رفض نقل الدم قد يؤدي إلى تدهور الحالة أو الوفاة في الحالات الحرجة.",
    specificEn: "I understand that transfusion of blood or blood products may be necessary to treat bleeding, anemia, or critical conditions. Risks may include allergy, fever, transfusion reaction, immune complications, fluid overload, and infection risks despite approved screening and verification measures. I understand that refusal may result in deterioration or death in critical cases.",
  },
  {
    categoryCode: "HIGH_RISK",
    categoryNameAr: "إجراءات عالية الخطورة",
    categoryNameEn: "High Risk",
    templateCode: "HIGH_RISK_MEDICAL_PROCEDURE_CONSENT",
    consentType: "HIGH_RISK_PROCEDURE_CONSENT",
    specialty: "GENERAL_MEDICINE",
    department: "CRITICAL_CARE",
    titleAr: "موافقة الإجراءات الطبية عالية الخطورة",
    titleEn: "High-Risk Medical Procedure Consent",
    summaryAr: "موافقة مخصصة للتدخلات عالية الخطورة وتبرير ضرورتها الطبية.",
    summaryEn: "Consent for high-risk interventions with medical necessity rationale.",
    riskLevel: "CRITICAL",
    requiresWitness: true,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
    specificAr: "تم إبلاغي بأن الإجراء مصنف عالي الخطورة وقد يؤدي إلى مضاعفات جسيمة مثل فقدان عضو أو منفعته، عجز دائم، فشل عضوي، نزيف شديد، عدوى خطيرة، دخول العناية المركزة، أو الوفاة لا قدر الله. وقد تم شرح سبب ضرورة الإجراء وعدم كفاية البدائل الأقل خطورة.",
    specificEn: "I have been informed that the procedure is classified as high-risk and may result in serious complications such as loss of organ or function, permanent disability, organ failure, severe bleeding, serious infection, ICU admission, or death. The medical necessity of the procedure and the insufficiency of lower-risk alternatives have been explained to me.",
  },
  {
    categoryCode: "SEDATION",
    categoryNameAr: "التهدئة الإجرائية",
    categoryNameEn: "Procedural Sedation",
    templateCode: "PROCEDURAL_SEDATION_CONSENT",
    consentType: "SEDATION_CONSENT",
    specialty: "ANESTHESIA",
    department: "ANESTHESIA",
    titleAr: "موافقة التهدئة والتسكين الإجرائي",
    titleEn: "Procedural Sedation Consent",
    summaryAr: "تحدد ضوابط التهدئة قبل وأثناء وبعد الإجراء.",
    summaryEn: "Defines sedation safeguards before, during, and after the procedure.",
    riskLevel: "HIGH",
    requiresWitness: false,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
    specificAr: "أفهم أن التهدئة الإجرائية قد تسبب النعاس، ضعف الوعي، انخفاض التنفس، انخفاض ضغط الدم، الغثيان، الحساسية، أو الحاجة إلى تدخل طبي عاجل. كما أفهم أنه يجب عدم القيادة أو اتخاذ قرارات مهمة بعد التهدئة حسب تعليمات الطبيب.",
    specificEn: "I understand that procedural sedation may cause drowsiness, reduced awareness, decreased breathing, low blood pressure, nausea, allergic reaction, or need for urgent medical intervention. I also understand that I should not drive or make important decisions after sedation as instructed by the physician.",
  },
  {
    categoryCode: "DAMA",
    categoryNameAr: "خروج ضد النصيحة الطبية",
    categoryNameEn: "DAMA",
    templateCode: "DAMA_DISCHARGE_AGAINST_MEDICAL_ADVICE",
    consentType: "DAMA_REFUSAL_OF_DISCHARGE",
    specialty: "EMERGENCY_MEDICINE",
    department: "EMERGENCY",
    titleAr: "إقرار الخروج ضد النصيحة الطبية",
    titleEn: "Discharge Against Medical Advice / DAMA",
    summaryAr: "يوثق طلب الخروج ضد التوصية الطبية وآثاره القانونية والطبية.",
    summaryEn: "Documents DAMA decision and its legal/medical consequences.",
    riskLevel: "CRITICAL",
    requiresWitness: true,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
    specificAr: "أقر بأنني طلبت الخروج من المستشفى أو رفضت الاستمرار في العلاج رغم توصية الفريق الطبي بالبقاء أو استكمال الخطة العلاجية. وقد تم شرح أن خروجي قد يؤدي إلى تدهور الحالة، مضاعفات خطيرة، فقدان فرصة علاجية، عجز دائم أو وفاة. وأقر بأنني أتحمل نتائج قراري، مع احتفاظي بحقي في العودة للطوارئ أو طلب الرعاية الطبية عند الحاجة.",
    specificEn: "I acknowledge that I requested discharge or refused continuation of treatment despite the medical team’s recommendation to remain admitted or complete the treatment plan. It has been explained to me that discharge may result in deterioration, serious complications, loss of treatment opportunity, permanent disability, or death. I accept the consequences of my decision while retaining my right to return to the emergency department or seek medical care when needed.",
  },
  {
    categoryCode: "SURGERY_REFUSAL",
    categoryNameAr: "رفض الجراحة",
    categoryNameEn: "Surgical Refusal",
    templateCode: "REFUSAL_OF_SURGICAL_PROCEDURE",
    consentType: "REFUSAL_OF_TREATMENT",
    specialty: "SURGERY",
    department: "GENERAL_SURGERY",
    titleAr: "إقرار رفض التدخل الجراحي",
    titleEn: "Refusal of Surgical Procedure",
    summaryAr: "إقرار رفض الجراحة بعد توضيح البدائل والمخاطر.",
    summaryEn: "Acknowledgment of surgery refusal after disclosure of consequences.",
    riskLevel: "HIGH",
    requiresWitness: true,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
    specificAr: "أقر بأن الطبيب شرح لي الحاجة الطبية للعملية الجراحية المقترحة ومخاطر رفضها، بما في ذلك استمرار المرض، تفاقم الحالة، زيادة صعوبة العلاج مستقبلاً، حدوث مضاعفات جسيمة أو الوفاة في الحالات الخطرة. ورغم ذلك، أرفض الإجراء الجراحي بإرادتي الحرة.",
    specificEn: "I acknowledge that the physician has explained the medical necessity of the proposed surgical procedure and the risks of refusal, including persistence of disease, worsening condition, increased difficulty of future treatment, serious complications, or death in high-risk cases. Nevertheless, I voluntarily refuse the surgical procedure.",
  },
  {
    categoryCode: "TELEMEDICINE",
    categoryNameAr: "الطب الاتصالي",
    categoryNameEn: "Telemedicine",
    templateCode: "TELEMEDICINE_CONSENT",
    consentType: "GENERAL_CONSENT",
    specialty: "GENERAL_MEDICINE",
    department: "VIRTUAL_CARE",
    titleAr: "موافقة خدمات الطب الاتصالي",
    titleEn: "Telemedicine Consent",
    summaryAr: "موافقة للخدمات الصحية عن بعد وتبادل البيانات إلكترونياً.",
    summaryEn: "Consent for remote care and secure electronic data exchange.",
    riskLevel: "MEDIUM",
    requiresWitness: false,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: false,
    specificAr: "أفهم أن خدمات الطب الاتصالي تتم عن بعد وقد تكون محدودة مقارنة بالفحص الحضوري، وأن ضعف الاتصال أو نقص المعلومات قد يؤثر على التقييم الطبي. وأوافق على استخدام الوسائل التقنية وتبادل البيانات الطبية بشكل آمن لغرض تقديم الخدمة.",
    specificEn: "I understand that telemedicine services are provided remotely and may be limited compared to in-person examination, and that connectivity issues or incomplete information may affect medical assessment. I consent to the use of technology and secure exchange of medical data for service delivery.",
  },
  {
    categoryCode: "PHOTOGRAPHY",
    categoryNameAr: "التصوير الطبي",
    categoryNameEn: "Medical Photography",
    templateCode: "MEDICAL_PHOTOGRAPHY_MEDIA_CONSENT",
    consentType: "GENERAL_CONSENT",
    specialty: "GENERAL_MEDICINE",
    department: "QUALITY",
    titleAr: "موافقة التصوير الطبي والإعلامي",
    titleEn: "Medical Photography and Media Consent",
    summaryAr: "تنظم التصوير الطبي للأغراض العلاجية والتعليمية والتوثيقية.",
    summaryEn: "Regulates medical imaging for care, education, and documentation.",
    riskLevel: "LOW",
    requiresWitness: false,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
    specificAr: "أوافق على التصوير الطبي لأغراض التشخيص أو العلاج أو التوثيق أو التعليم أو الجودة، وفق نطاق الموافقة المحدد. ولا يجوز استخدام الصور لأغراض إعلامية أو تسويقية خارجية إلا بموافقة مستقلة وصريحة، مع مراعاة حماية الهوية والخصوصية.",
    specificEn: "I consent to medical photography for diagnosis, treatment, documentation, education, or quality purposes within the defined scope of consent. Images shall not be used for external media or marketing purposes without separate explicit consent, while maintaining identity and privacy protection.",
  },
  {
    categoryCode: "PDPL_HEALTH_DATA",
    categoryNameAr: "بيانات صحية شخصية",
    categoryNameEn: "Health Data PDPL",
    templateCode: "HEALTH_PERSONAL_DATA_PROCESSING_SHARING_CONSENT",
    consentType: "GENERAL_CONSENT",
    specialty: "GENERAL_MEDICINE",
    department: "LEGAL_COMPLIANCE",
    titleAr: "موافقة معالجة ومشاركة البيانات الشخصية الصحية",
    titleEn: "Health Personal Data Processing and Sharing Consent",
    summaryAr: "موافقة PDPL لمعالجة ومشاركة البيانات الصحية.",
    summaryEn: "PDPL consent for processing and sharing personal health data.",
    riskLevel: "MEDIUM",
    requiresWitness: false,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
    specificAr: "أوافق على معالجة بياناتي الصحية والشخصية لأغراض الرعاية الصحية، إدارة الملف الطبي، الجودة، سلامة المرضى، المطالبات، التقارير التنظيمية، المراجعة الداخلية، والدفاع عن الحقوق النظامية. وأفهم أن مشاركة البيانات تتم وفق الأنظمة المعمول بها ومع الجهات المختصة أو مقدمي الخدمة المصرح لهم عند الحاجة.",
    specificEn: "I consent to the processing of my personal and health data for healthcare delivery, medical record management, quality, patient safety, claims, regulatory reporting, internal review, and protection of legal rights. I understand that data sharing shall occur in accordance with applicable laws and with competent authorities or authorized service providers where necessary.",
  },
  {
    categoryCode: "RESEARCH",
    categoryNameAr: "الأبحاث الطبية",
    categoryNameEn: "Research",
    templateCode: "RESEARCH_PARTICIPATION_CONSENT",
    consentType: "RESEARCH_CLINICAL_TRIAL_CONSENT",
    specialty: "GENERAL_MEDICINE",
    department: "RESEARCH",
    titleAr: "موافقة المشاركة في الأبحاث والدراسات الطبية",
    titleEn: "Research Participation Consent",
    summaryAr: "موافقة أخلاقية للمشاركة البحثية مع حق الانسحاب.",
    summaryEn: "Ethical research participation consent with right to withdraw.",
    riskLevel: "HIGH",
    requiresWitness: true,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
    specificAr: "أفهم أن المشاركة في البحث اختيارية، وأنه تم شرح هدف الدراسة، مدتها، إجراءاتها، المنافع المتوقعة، المخاطر المحتملة، حماية السرية، واستخدام البيانات أو العينات. وأفهم أن لي الحق في الانسحاب في أي وقت دون أن يؤثر ذلك على حقي في تلقي الرعاية الطبية.",
    specificEn: "I understand that participation in research is voluntary, and that the study purpose, duration, procedures, expected benefits, potential risks, confidentiality safeguards, and use of data or samples have been explained to me. I understand that I may withdraw at any time without affecting my right to receive medical care.",
  },
  {
    categoryCode: "CHEMOTHERAPY",
    categoryNameAr: "العلاج الكيميائي",
    categoryNameEn: "Chemotherapy",
    templateCode: "CHEMOTHERAPY_CONSENT",
    consentType: "PROCEDURE_SPECIFIC_CONSENT",
    specialty: "ONCOLOGY",
    department: "ONCOLOGY",
    titleAr: "موافقة العلاج الكيميائي",
    titleEn: "Chemotherapy Consent",
    summaryAr: "موافقة مخصصة للعلاج الكيميائي ومضاعفاته الجهازية.",
    summaryEn: "Procedure-specific chemotherapy consent and systemic adverse effects.",
    riskLevel: "CRITICAL",
    requiresWitness: true,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
    specificAr: "أفهم أن العلاج الكيميائي قد يسبب تساقط الشعر، الغثيان، القيء، ضعف المناعة، العدوى، النزيف، التعب، اضطرابات الكبد أو الكلى أو القلب، التأثير على الخصوبة، العقم المؤقت أو الدائم، الحاجة إلى نقل الدم أو الدخول للمستشفى، وفي حالات نادرة مضاعفات مهددة للحياة.",
    specificEn: "I understand that chemotherapy may cause hair loss, nausea, vomiting, immunosuppression, infection, bleeding, fatigue, liver, kidney or cardiac complications, fertility effects, temporary or permanent infertility, need for blood transfusion or hospitalization, and in rare cases life-threatening complications.",
  },
  {
    categoryCode: "RADIOTHERAPY",
    categoryNameAr: "العلاج الإشعاعي",
    categoryNameEn: "Radiotherapy",
    templateCode: "RADIOTHERAPY_CONSENT",
    consentType: "PROCEDURE_SPECIFIC_CONSENT",
    specialty: "ONCOLOGY",
    department: "RADIATION_ONCOLOGY",
    titleAr: "موافقة العلاج الإشعاعي",
    titleEn: "Radiotherapy Consent",
    summaryAr: "موافقة العلاج الإشعاعي مع الآثار قصيرة وطويلة الأمد.",
    summaryEn: "Radiotherapy consent with short- and long-term effects.",
    riskLevel: "HIGH",
    requiresWitness: true,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
    specificAr: "أفهم أن العلاج الإشعاعي قد يسبب احمرار الجلد، التعب، الألم، الغثيان، تهيج الأنسجة، تغيرات طويلة المدى في الأعضاء المعالجة، تأثيراً على الخصوبة بحسب موقع العلاج، واحتمال حدوث مضاعفات متأخرة. وقد تم شرح البدائل المتاحة.",
    specificEn: "I understand that radiotherapy may cause skin redness, fatigue, pain, nausea, tissue irritation, long-term changes in treated organs, fertility impact depending on treatment site, and possible delayed complications. Available alternatives have been explained.",
  },
  {
    categoryCode: "CONTRAST_RADIOLOGY",
    categoryNameAr: "الصبغة والإشعاع",
    categoryNameEn: "Contrast Radiology",
    templateCode: "CONTRAST_MEDIA_RADIOLOGICAL_PROCEDURE_CONSENT",
    consentType: "RADIOLOGY_CONTRAST_CONSENT",
    specialty: "RADIOLOGY",
    department: "RADIOLOGY",
    titleAr: "موافقة استخدام الصبغة والإجراءات الإشعاعية",
    titleEn: "Contrast Media and Radiological Procedure Consent",
    summaryAr: "موافقة مخصصة لاستخدام الصبغة في الإجراءات الشعاعية.",
    summaryEn: "Consent for contrast-enhanced radiological procedures.",
    riskLevel: "HIGH",
    requiresWitness: false,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
    specificAr: "أفهم أن استخدام الصبغة قد يكون ضرورياً لتحسين دقة التشخيص، وقد يسبب حساسية، غثيان، حكة، طفح جلدي، ضيق تنفس، انخفاض ضغط الدم، تأثيراً على وظائف الكلى، أو تفاعلات نادرة خطيرة. وقد تم إبلاغي بضرورة الإفصاح عن الحساسية أو أمراض الكلى أو الحمل.",
    specificEn: "I understand that contrast media may be necessary to improve diagnostic accuracy and may cause allergy, nausea, itching, rash, breathing difficulty, low blood pressure, kidney function impact, or rare severe reactions. I have been informed of the need to disclose allergies, kidney disease, or pregnancy.",
  },
  {
    categoryCode: "ICU_CRITICAL_CARE",
    categoryNameAr: "العناية المركزة",
    categoryNameEn: "ICU Critical Care",
    templateCode: "ICU_CRITICAL_CARE_CONSENT",
    consentType: "HIGH_RISK_PROCEDURE_CONSENT",
    specialty: "ICU",
    department: "ICU",
    titleAr: "موافقة العناية المركزة والإجراءات الحرجة",
    titleEn: "ICU and Critical Care Consent",
    summaryAr: "موافقة للتدخلات الحرجة في العناية المركزة.",
    summaryEn: "Consent for ICU life-support and critical interventions.",
    riskLevel: "CRITICAL",
    requiresWitness: true,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
    specificAr: "أفهم أن العناية المركزة قد تتطلب مراقبة مستمرة، أجهزة تنفس صناعي، قساطر وريدية أو شريانية، أدوية داعمة للضغط، تغذية أنبوبية، غسيل كلوي، إنعاش قلبي رئوي، أو تدخلات طارئة. وقد تشمل المخاطر العدوى، النزيف، فشل الأعضاء، المضاعفات الدوائية، أو الوفاة رغم تقديم الرعاية المناسبة.",
    specificEn: "I understand that ICU care may require continuous monitoring, mechanical ventilation, venous or arterial lines, vasopressor medications, tube feeding, dialysis, cardiopulmonary resuscitation, or emergency interventions. Risks may include infection, bleeding, organ failure, medication-related complications, or death despite appropriate care.",
  },
  {
    categoryCode: "HOME_HEALTHCARE",
    categoryNameAr: "الرعاية المنزلية",
    categoryNameEn: "Home Healthcare",
    templateCode: "HOME_HEALTHCARE_SERVICES_CONSENT",
    consentType: "GENERAL_CONSENT",
    specialty: "GENERAL_MEDICINE",
    department: "HOME_HEALTHCARE",
    titleAr: "موافقة خدمات الرعاية الصحية المنزلية",
    titleEn: "Home Healthcare Services Consent",
    summaryAr: "موافقة خدمات الرعاية المنزلية مع شروط السلامة والإحالة.",
    summaryEn: "Consent for home care services with safety and escalation controls.",
    riskLevel: "MEDIUM",
    requiresWitness: false,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: false,
    specificAr: "أفهم أن الرعاية الصحية المنزلية تقدم خارج بيئة المستشفى، وقد تشمل التمريض، العلاج الطبيعي، إعطاء الأدوية، العناية بالجروح، المتابعة، أو الأجهزة الطبية المنزلية. وأفهم أن بعض الحالات قد تتطلب الإحالة للطوارئ أو المستشفى عند التدهور، وأن سلامة البيئة المنزلية وتعاون المريض أو أسرته ضروريان.",
    specificEn: "I understand that home healthcare is provided outside the hospital setting and may include nursing care, physiotherapy, medication administration, wound care, follow-up, or home medical devices. I understand that deterioration may require referral to emergency or hospital care, and that home safety and patient/family cooperation are necessary.",
  },
  {
    categoryCode: "INTERVENTIONAL",
    categoryNameAr: "إجراءات تداخلية",
    categoryNameEn: "Interventional",
    templateCode: "SPECIAL_INTERVENTIONAL_PROCEDURE_CONSENT",
    consentType: "PROCEDURE_SPECIFIC_CONSENT",
    specialty: "RADIOLOGY",
    department: "INTERVENTIONAL",
    titleAr: "موافقة الإجراءات الخاصة والتداخلية",
    titleEn: "Special and Interventional Procedure Consent",
    summaryAr: "موافقة للإجراءات التداخلية الخاصة بمخاطرها المعروفة.",
    summaryEn: "Consent for special interventional procedures and their known risks.",
    riskLevel: "HIGH",
    requiresWitness: true,
    requiresGuardian: false,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
    specificAr: "أفهم أن الإجراء الخاص أو التداخلي قد يتضمن إدخال أدوات أو قساطر أو إبر أو مناظير أو أجهزة داخل الجسم، وقد يترتب عليه نزيف، عدوى، ثقب عضو، ألم، فشل الإجراء، الحاجة إلى تدخل إضافي، أو مضاعفات جسيمة بحسب نوع الإجراء.",
    specificEn: "I understand that the special or interventional procedure may involve insertion of instruments, catheters, needles, scopes, or devices into the body, and may result in bleeding, infection, organ perforation, pain, failure of the procedure, need for further intervention, or serious complications depending on the type of procedure.",
  },
  {
    categoryCode: "MINOR_GUARDIAN",
    categoryNameAr: "موافقة ولي الأمر",
    categoryNameEn: "Minor/Guardian",
    templateCode: "MINOR_GUARDIAN_CONSENT",
    consentType: "GENERAL_CONSENT",
    specialty: "PEDIATRICS",
    department: "PEDIATRICS",
    titleAr: "موافقة ولي الأمر / القاصر / فاقد الأهلية",
    titleEn: "Minor / Guardian Consent",
    summaryAr: "موافقة مخصصة للقاصر أو فاقد الأهلية عبر الممثل النظامي.",
    summaryEn: "Consent for minors/incapacitated patients via legal representative.",
    riskLevel: "HIGH",
    requiresWitness: true,
    requiresGuardian: true,
    requiresInterpreter: false,
    requiresSeparateConsent: true,
    specificAr: "أقر بصفتي ولياً أو ممثلاً نظامياً للمريض القاصر أو فاقد الأهلية أو ناقصها بأنني أملك الصفة النظامية لإعطاء هذه الموافقة، وأن قراري يحقق مصلحة المريض ورفع الضرر عنه. وأفهم أنه في الحالات الطارئة المهددة للحياة يجوز للفريق الطبي اتخاذ التدخل اللازم وفق الضوابط النظامية عند تعذر الحصول على الإذن.",
    specificEn: "I confirm that I am the legal guardian or authorized representative of the minor, incapacitated, or partially incapacitated patient, and that I have the legal authority to provide this consent. I confirm that my decision is made in the patient’s best interest and to prevent harm. I understand that in life-threatening emergencies, the medical team may proceed with necessary intervention in accordance with applicable legal requirements when consent cannot be obtained.",
  },
];

export function buildSaudiTemplateBodyAr(seed: SaudiEnterpriseTemplateSeed): string {
  return [
    seed.titleAr,
    "",
    AR_INTRO,
    "",
    AR_INTRO_2,
    "",
    "النص الخاص بالنموذج:",
    seed.specificAr,
    "",
    "الخصوصية وحماية البيانات:",
    AR_PDPL,
    "",
    "الإقرار النهائي:",
    AR_VOLUNTARY,
    "",
    "عدم ضمان النتيجة:",
    AR_NO_GUARANTEE,
  ].join("\n");
}

export function buildSaudiTemplateBodyEn(seed: SaudiEnterpriseTemplateSeed): string {
  return [
    seed.titleEn,
    "",
    EN_INTRO,
    "",
    EN_INTRO_2,
    "",
    "Template-specific wording:",
    seed.specificEn,
    "",
    "Privacy and Data Protection:",
    EN_PDPL,
    "",
    "Final Consent:",
    EN_VOLUNTARY,
    "",
    "No Guarantee of Outcome:",
    EN_NO_GUARANTEE,
  ].join("\n");
}

export function buildSaudiTemplateSections(seed: SaudiEnterpriseTemplateSeed): SectionSeed[] {
  return [
    {
      sectionKey: "01_consent_title",
      sectionKind: ConsentSectionKind.FIXED_LEGAL,
      titleAr: "عنوان الموافقة",
      titleEn: "Consent Title",
      contentAr: seed.titleAr,
      contentEn: seed.titleEn,
      isRequired: true,
      isEditableByPhysician: false,
      sortOrder: 10,
    },
    {
      sectionKey: "02_patient_information",
      sectionKind: ConsentSectionKind.DYNAMIC_MEDICAL,
      titleAr: "بيانات المريض",
      titleEn: "Patient Information",
      contentAr: "- اسم المريض\n- رقم الملف الطبي\n- رقم الهوية / الإقامة\n- تاريخ الميلاد\n- العمر\n- الجنس\n- رقم التواصل\n- اللغة المفضلة\n- الحاجة إلى مترجم: نعم / لا",
      contentEn: "- Patient Name\n- MRN\n- National ID / Iqama\n- Date of Birth\n- Age\n- Gender\n- Contact Number\n- Preferred Language\n- Interpreter Required: Yes / No",
      isRequired: true,
      isEditableByPhysician: true,
      sortOrder: 20,
    },
    {
      sectionKey: "03_physician_information",
      sectionKind: ConsentSectionKind.DYNAMIC_MEDICAL,
      titleAr: "بيانات الطبيب / الممارس الصحي",
      titleEn: "Physician / Practitioner Information",
      contentAr: "- اسم الطبيب\n- التخصص\n- القسم\n- رقم الترخيص المهني\n- اسم المنشأة",
      contentEn: "- Physician Name\n- Specialty\n- Department\n- Professional License Number\n- Facility Name",
      isRequired: true,
      isEditableByPhysician: true,
      sortOrder: 30,
    },
    {
      sectionKey: "04_description",
      sectionKind: ConsentSectionKind.DYNAMIC_MEDICAL,
      titleAr: "وصف الإجراء / العلاج / الخدمة",
      titleEn: "Description of Procedure / Treatment / Service",
      contentAr: `وصف الحالة والإجراء المقترح:\n${seed.specificAr}`,
      contentEn: `Description and template-specific scope:\n${seed.specificEn}`,
      isRequired: true,
      isEditableByPhysician: true,
      sortOrder: 40,
    },
    {
      sectionKey: "05_diagnosis_indication",
      sectionKind: ConsentSectionKind.DYNAMIC_MEDICAL,
      titleAr: "التشخيص / الداعي الطبي",
      titleEn: "Diagnosis / Indication",
      contentAr: "[يُدخل الطبيب التشخيص أو السبب الطبي]",
      contentEn: "[Physician enters diagnosis/medical indication]",
      isRequired: true,
      isEditableByPhysician: true,
      sortOrder: 50,
    },
    {
      sectionKey: "06_expected_benefits",
      sectionKind: ConsentSectionKind.DYNAMIC_MEDICAL,
      titleAr: "المنافع المتوقعة",
      titleEn: "Expected Benefits",
      contentAr: `- ${AR_STANDARD_BENEFITS}`,
      contentEn: `- ${EN_STANDARD_BENEFITS}`,
      isRequired: true,
      isEditableByPhysician: true,
      sortOrder: 60,
    },
    {
      sectionKey: "07_material_risks",
      sectionKind: ConsentSectionKind.DYNAMIC_MEDICAL,
      titleAr: "المخاطر الجوهرية",
      titleEn: "Material Risks",
      contentAr: `- ${AR_STANDARD_RISKS}`,
      contentEn: `- ${EN_STANDARD_RISKS}`,
      isRequired: true,
      isEditableByPhysician: true,
      sortOrder: 70,
    },
    {
      sectionKey: "08_possible_complications",
      sectionKind: ConsentSectionKind.DYNAMIC_MEDICAL,
      titleAr: "المضاعفات المحتملة",
      titleEn: "Possible Complications",
      contentAr: "[المضاعفات المحتملة وفق الحالة السريرية]",
      contentEn: "[Potential complications according to clinical context]",
      isRequired: true,
      isEditableByPhysician: true,
      sortOrder: 80,
    },
    {
      sectionKey: "09_serious_complications",
      sectionKind: ConsentSectionKind.DYNAMIC_MEDICAL,
      titleAr: "المضاعفات الجسيمة",
      titleEn: "Serious Complications",
      contentAr: `- ${AR_STANDARD_SERIOUS}`,
      contentEn: `- ${EN_STANDARD_SERIOUS}`,
      isRequired: true,
      isEditableByPhysician: true,
      sortOrder: 90,
    },
    {
      sectionKey: "10_alternatives",
      sectionKind: ConsentSectionKind.DYNAMIC_MEDICAL,
      titleAr: "البدائل",
      titleEn: "Alternative Options",
      contentAr: `- ${AR_STANDARD_ALTERNATIVES}`,
      contentEn: `- ${EN_STANDARD_ALTERNATIVES}`,
      isRequired: true,
      isEditableByPhysician: true,
      sortOrder: 100,
    },
    {
      sectionKey: "11_refusal_consequences",
      sectionKind: ConsentSectionKind.DYNAMIC_MEDICAL,
      titleAr: "نتائج الرفض أو التأجيل",
      titleEn: "Consequences of Refusal or Delay",
      contentAr: `- ${AR_STANDARD_REFUSAL}`,
      contentEn: `- ${EN_STANDARD_REFUSAL}`,
      isRequired: true,
      isEditableByPhysician: true,
      sortOrder: 110,
    },
    {
      sectionKey: "12_questions_confirmation",
      sectionKind: ConsentSectionKind.FIXED_LEGAL,
      titleAr: "إقرار بالشرح والفهم",
      titleEn: "Questions and Explanation Confirmation",
      contentAr: AR_INTRO_2,
      contentEn: EN_INTRO_2,
      isRequired: true,
      isEditableByPhysician: false,
      sortOrder: 120,
    },
    {
      sectionKey: "13_voluntary_statement",
      sectionKind: ConsentSectionKind.FIXED_LEGAL,
      titleAr: "بيان الموافقة الطوعية",
      titleEn: "Voluntary Consent Statement",
      contentAr: AR_VOLUNTARY,
      contentEn: EN_VOLUNTARY,
      isRequired: true,
      isEditableByPhysician: false,
      sortOrder: 130,
    },
    {
      sectionKey: "14_no_guarantee",
      sectionKind: ConsentSectionKind.FIXED_LEGAL,
      titleAr: "عدم ضمان النتيجة",
      titleEn: "No Guarantee of Outcome",
      contentAr: AR_NO_GUARANTEE,
      contentEn: EN_NO_GUARANTEE,
      isRequired: true,
      isEditableByPhysician: false,
      sortOrder: 140,
    },
    {
      sectionKey: "15_right_to_refuse_withdraw",
      sectionKind: ConsentSectionKind.FIXED_LEGAL,
      titleAr: "حق الرفض أو السحب",
      titleEn: "Right to Refuse / Withdraw",
      contentAr: "أفهم أن لي الحق في رفض الإجراء أو سحب الموافقة قبل التنفيذ، مع تحملي للنتائج الطبية المترتبة على ذلك.",
      contentEn: "I understand that I have the right to refuse or withdraw consent before procedure execution, with acceptance of the resulting medical consequences.",
      isRequired: true,
      isEditableByPhysician: false,
      sortOrder: 150,
    },
    {
      sectionKey: "16_pdpl_clause",
      sectionKind: ConsentSectionKind.FIXED_LEGAL,
      titleAr: "بند الخصوصية وحماية البيانات",
      titleEn: "PDPL and Data Processing Clause",
      contentAr: AR_PDPL,
      contentEn: EN_PDPL,
      isRequired: true,
      isEditableByPhysician: false,
      sortOrder: 160,
    },
    {
      sectionKey: "17_guardian_clause",
      sectionKind: ConsentSectionKind.FIXED_LEGAL,
      titleAr: "بند ولي الأمر / الممثل",
      titleEn: "Guardian / Representative Clause",
      contentAr: "يُستكمل هذا البند عند توقيع ولي أمر أو ممثل نظامي مع إثبات الصفة النظامية.",
      contentEn: "This clause must be completed when signed by a legal guardian/representative with proof of authority.",
      isRequired: seed.requiresGuardian,
      isEditableByPhysician: false,
      sortOrder: 170,
    },
    {
      sectionKey: "18_interpreter_clause",
      sectionKind: ConsentSectionKind.INTERPRETER,
      titleAr: "بند المترجم",
      titleEn: "Interpreter Clause",
      contentAr: "يُستكمل هذا البند إذا كانت لغة المريض لا تتطابق مع لغة نموذج الموافقة.",
      contentEn: "This clause must be completed when the patient language differs from consent form language.",
      isRequired: seed.requiresInterpreter,
      isEditableByPhysician: false,
      sortOrder: 180,
    },
    {
      sectionKey: "19_witness_clause",
      sectionKind: ConsentSectionKind.WITNESS,
      titleAr: "بند الشاهد",
      titleEn: "Witness Clause",
      contentAr: "يُثبت الشاهد أن الشرح تم وأن التوقيع تم بإرادة حرة.",
      contentEn: "Witness confirms that explanation was provided and signature was voluntary.",
      isRequired: seed.requiresWitness,
      isEditableByPhysician: false,
      sortOrder: 190,
    },
    {
      sectionKey: "20_physician_declaration",
      sectionKind: ConsentSectionKind.FIXED_LEGAL,
      titleAr: "إقرار الطبيب",
      titleEn: "Physician Declaration",
      contentAr: "أقر كطبيب مرخص أنني شرحت للمريض كافة المعلومات الجوهرية بلغة مفهومة.",
      contentEn: "As a licensed physician, I certify that I explained all material information in understandable language.",
      isRequired: true,
      isEditableByPhysician: false,
      sortOrder: 200,
    },
    {
      sectionKey: "21_patient_ack",
      sectionKind: ConsentSectionKind.FIXED_LEGAL,
      titleAr: "إقرار المريض / الولي",
      titleEn: "Patient / Guardian Acknowledgment",
      contentAr: "أقر بأنني قرأت وفهمت ووافقت دون إكراه.",
      contentEn: "I acknowledge that I have read, understood, and consented without coercion.",
      isRequired: true,
      isEditableByPhysician: false,
      sortOrder: 210,
    },
    {
      sectionKey: "22_signature_block",
      sectionKind: ConsentSectionKind.SIGNATURE,
      titleAr: "كتلة التوقيعات",
      titleEn: "Signature Block",
      contentAr: "- اسم المريض/الولي\n- الصفة\n- التوقيع\n- التاريخ والوقت\n- اسم الطبيب وتوقيعه\n- اسم الشاهد وتوقيعه\n- اسم المترجم وتوقيعه",
      contentEn: "- Patient/Guardian Name\n- Capacity\n- Signature\n- Date & Time\n- Physician Name/Signature\n- Witness Name/Signature\n- Interpreter Name/Signature",
      isRequired: true,
      isEditableByPhysician: false,
      sortOrder: 220,
    },
    {
      sectionKey: "23_otp_validation",
      sectionKind: ConsentSectionKind.SIGNATURE,
      titleAr: "التحقق الإلكتروني OTP",
      titleEn: "OTP / Electronic Signature Validation",
      contentAr: "لا يُعتد بالإغلاق النهائي حتى تحقق OTP أو توقيع رقمي موثوق.",
      contentEn: "Final sealing is blocked until OTP verification or trusted digital signature is completed.",
      isRequired: true,
      isEditableByPhysician: false,
      sortOrder: 230,
    },
    {
      sectionKey: "24_qr_verification",
      sectionKind: ConsentSectionKind.FIXED_LEGAL,
      titleAr: "التحقق عبر QR",
      titleEn: "QR Verification",
      contentAr: "يتم تضمين رمز QR للتحقق من أصالة المستند وسلامة التجزئة القانونية.",
      contentEn: "A QR code is included to verify document authenticity and legal hash integrity.",
      isRequired: true,
      isEditableByPhysician: false,
      sortOrder: 240,
    },
    {
      sectionKey: "25_legal_seal_audit",
      sectionKind: ConsentSectionKind.FIXED_LEGAL,
      titleAr: "الختم القانوني وسجل التدقيق",
      titleEn: "Legal Seal and Audit Trail",
      contentAr: "يُختم المستند بخلاصة قانونية (هاش الختم القانوني) مع ربط كامل بسجل تدقيق غير قابل للتلاعب.",
      contentEn: "The document is sealed with a legal hash and linked to an immutable audit trail.",
      isRequired: true,
      isEditableByPhysician: false,
      sortOrder: 250,
    },
  ];
}
