BEGIN;

ALTER TABLE secure_discharge_links
  ADD COLUMN IF NOT EXISTS decision_type VARCHAR NULL,
  ADD COLUMN IF NOT EXISTS decision_name VARCHAR NULL,
  ADD COLUMN IF NOT EXISTS decision_submitted_at TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS decision_ip_address VARCHAR NULL,
  ADD COLUMN IF NOT EXISTS decision_user_agent TEXT NULL,
  ADD COLUMN IF NOT EXISTS refusal_acknowledged_at TIMESTAMP NULL;

COMMIT;