-- Medical Discharge Refusal Workflow schema extension
-- Safe additive migration for PostgreSQL.

BEGIN;

ALTER TABLE IF EXISTS discharge_refusal_workflows
  ADD COLUMN IF NOT EXISTS case_status VARCHAR NOT NULL DEFAULT 'Draft',
  ADD COLUMN IF NOT EXISTS closed_at TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS escalation_timestamp TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS patient_id VARCHAR NULL,
  ADD COLUMN IF NOT EXISTS mrn VARCHAR NULL,
  ADD COLUMN IF NOT EXISTS nursing_notes TEXT NULL,
  ADD COLUMN IF NOT EXISTS patient_affairs_notes TEXT NULL,
  ADD COLUMN IF NOT EXISTS social_services_notes TEXT NULL,
  ADD COLUMN IF NOT EXISTS quality_notes TEXT NULL,
  ADD COLUMN IF NOT EXISTS compliance_notes TEXT NULL,
  ADD COLUMN IF NOT EXISTS legal_notes TEXT NULL,
  ADD COLUMN IF NOT EXISTS financial_notice_issued BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS financial_notice_acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS refusal_form_signed BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS patient_signature TEXT NULL,
  ADD COLUMN IF NOT EXISTS representative_signature TEXT NULL,
  ADD COLUMN IF NOT EXISTS witness_mode BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS witness1_name VARCHAR NULL,
  ADD COLUMN IF NOT EXISTS witness1_role VARCHAR NULL,
  ADD COLUMN IF NOT EXISTS witness1_signature TEXT NULL,
  ADD COLUMN IF NOT EXISTS witness2_name VARCHAR NULL,
  ADD COLUMN IF NOT EXISTS witness2_role VARCHAR NULL,
  ADD COLUMN IF NOT EXISTS witness2_signature TEXT NULL;

ALTER TABLE IF EXISTS discharge_workflow_documents
  ADD COLUMN IF NOT EXISTS locale VARCHAR NOT NULL DEFAULT 'en',
  ADD COLUMN IF NOT EXISTS template_version VARCHAR NOT NULL DEFAULT '1.0',
  ADD COLUMN IF NOT EXISTS locked_template BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS signed_at TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS signed_by VARCHAR NULL,
  ADD COLUMN IF NOT EXISTS attachment_group VARCHAR NULL;

COMMIT;
