import { renderPdfDocumentShell } from "@/lib/pdf-engine/core/pdf-renderer";
import { formatEvidenceValue, renderDefinitionRows, renderSection } from "@/lib/pdf-engine/core/pdf-layout";
import { buildPdfLanguageLayoutFlags } from "@/lib/pdf-engine/core/pdf-rtl";
import type { InformedConsentEvidenceHtmlPayload, PdfEvidenceLanguage } from "@/lib/pdf-engine/core/pdf-types";

type TemplateCopy = {
  documentTitle: string;
  patientBlock: string;
  encounterBlock: string;
  consentBlock: string;
  evidenceBlock: string;
  qrBlock: string;
  patientMrn: string;
  patientName: string;
  caseNumber: string;
  encounterNo: string;
  consentVersion: string;
  consentTitle: string;
  consentType: string;
  templateName: string;
  physicianName: string;
  documentId: string;
  evidenceId: string;
  auditId: string;
  tenantId: string;
  moduleKey: string;
  generatedAt: string;
  generatedBy: string;
  verificationUrl: string;
  hash: string;
  qrPlaceholder: string;
};

const TEMPLATE_COPY: Record<PdfEvidenceLanguage, TemplateCopy> = {
  en: {
    documentTitle: "Informed Consent Legal Evidence Preview",
    patientBlock: "Patient Information",
    encounterBlock: "Encounter Information",
    consentBlock: "Consent Information",
    evidenceBlock: "Evidence Metadata",
    qrBlock: "Verification QR",
    patientMrn: "Patient MRN",
    patientName: "Patient Name",
    caseNumber: "Case Number",
    encounterNo: "Encounter No.",
    consentVersion: "Consent Version",
    consentTitle: "Consent Title",
    consentType: "Consent Type",
    templateName: "Template Name",
    physicianName: "Treating Physician",
    documentId: "Document ID",
    evidenceId: "Evidence ID",
    auditId: "Audit ID",
    tenantId: "Tenant ID",
    moduleKey: "Module Key",
    generatedAt: "Generated At",
    generatedBy: "Generated By",
    verificationUrl: "Verification URL",
    hash: "SHA-256 Hash",
    qrPlaceholder: "QR preview will appear here when generated.",
  },
  ar: {
    documentTitle: "معاينة الإثبات القانوني للموافقة المستنيرة",
    patientBlock: "بيانات المريض",
    encounterBlock: "بيانات الزيارة",
    consentBlock: "بيانات الموافقة",
    evidenceBlock: "بيانات الإثبات",
    qrBlock: "رمز التحقق",
    patientMrn: "الرقم الطبي",
    patientName: "اسم المريض",
    caseNumber: "رقم الحالة",
    encounterNo: "رقم الزيارة",
    consentVersion: "إصدار الموافقة",
    consentTitle: "عنوان الموافقة",
    consentType: "نوع الموافقة",
    templateName: "اسم القالب",
    physicianName: "الطبيب المعالج",
    documentId: "معرف المستند",
    evidenceId: "معرف الإثبات",
    auditId: "معرف التدقيق",
    tenantId: "معرف الجهة",
    moduleKey: "مفتاح الوحدة",
    generatedAt: "تاريخ الإنشاء",
    generatedBy: "تم الإنشاء بواسطة",
    verificationUrl: "رابط التحقق",
    hash: "بصمة SHA-256",
    qrPlaceholder: "سيظهر رمز التحقق هنا عند توليده.",
  },
};

function buildQrBlock(payload: InformedConsentEvidenceHtmlPayload, copy: TemplateCopy): string {
  const verificationUrl = formatEvidenceValue(payload.evidence.verificationUrl);
  const imageHtml = payload.evidence.qrDataUrl
    ? `<img class="wc-pdf-qr-image" src="${payload.evidence.qrDataUrl}" alt="QR verification" />`
    : `<div class="wc-pdf-note">${copy.qrPlaceholder}</div>`;

  return renderSection(
    copy.qrBlock,
    `<div class="wc-pdf-qr-placeholder">
      ${imageHtml}
      <div class="wc-pdf-note">${verificationUrl}</div>
    </div>`,
  );
}

export function buildInformedConsentTemplatePayload(payload: InformedConsentEvidenceHtmlPayload): InformedConsentEvidenceHtmlPayload {
  return payload;
}

export function renderInformedConsentTemplate(payload: InformedConsentEvidenceHtmlPayload): string {
  const language = payload.evidence.language;
  const flags = buildPdfLanguageLayoutFlags(language);
  const copy = TEMPLATE_COPY[language];

  const patientHtml = renderSection(
    copy.patientBlock,
    renderDefinitionRows([
      { label: copy.patientName, value: formatEvidenceValue(payload.evidence.patientName) },
      { label: copy.patientMrn, value: formatEvidenceValue(payload.evidence.patientMrn) },
    ]),
  );

  const encounterHtml = renderSection(
    copy.encounterBlock,
    renderDefinitionRows([
      { label: copy.caseNumber, value: formatEvidenceValue(payload.evidence.caseNumber) },
      { label: copy.encounterNo, value: formatEvidenceValue(payload.evidence.encounterNo) },
      { label: copy.physicianName, value: formatEvidenceValue(payload.physicianName) },
    ]),
  );

  const consentHtml = renderSection(
    copy.consentBlock,
    renderDefinitionRows([
      { label: copy.consentVersion, value: formatEvidenceValue(payload.evidence.consentVersion) },
      { label: copy.consentTitle, value: formatEvidenceValue(payload.consentTitle) },
      { label: copy.consentType, value: formatEvidenceValue(payload.consentType) },
      { label: copy.templateName, value: formatEvidenceValue(payload.templateName) },
    ]) + (payload.renderedBodyHtml ? `<div class="wc-pdf-note">${payload.renderedBodyHtml}</div>` : ""),
  );

  const evidenceHtml = renderSection(
    copy.evidenceBlock,
    renderDefinitionRows([
      { label: copy.documentId, value: formatEvidenceValue(payload.evidence.documentId) },
      { label: copy.evidenceId, value: formatEvidenceValue(payload.evidence.evidenceId) },
      { label: copy.auditId, value: formatEvidenceValue(payload.evidence.auditId) },
      { label: copy.tenantId, value: formatEvidenceValue(payload.evidence.tenantId) },
      { label: copy.moduleKey, value: formatEvidenceValue(payload.evidence.moduleKey) },
      { label: copy.generatedAt, value: formatEvidenceValue(payload.evidence.generatedAt) },
      { label: copy.generatedBy, value: formatEvidenceValue(payload.evidence.generatedBy) },
      { label: copy.hash, value: formatEvidenceValue(payload.evidence.hash) },
      { label: copy.verificationUrl, value: formatEvidenceValue(payload.evidence.verificationUrl) },
    ]),
  );

  return renderPdfDocumentShell({
    lang: flags.language,
    dir: flags.dir,
    title: copy.documentTitle,
    bodyHtml: [patientHtml, encounterHtml, consentHtml, evidenceHtml, buildQrBlock(payload, copy)].join(""),
    footerText: payload.evidence.legalFooterText,
    referenceNumber: payload.evidence.documentId,
    version: payload.evidence.consentVersion || "v1.0",
    generatedAt: payload.evidence.generatedAt,
    watermarkLabel: payload.evidence.evidenceId,
    qrPayload: payload.evidence.verificationUrl,
    documentHash: payload.evidence.hash,
    evidenceId: payload.evidence.evidenceId,
    auditReferenceId: payload.evidence.auditId,
    immutableSeal: payload.evidence.legalRuntime?.immutableSeal || null,
    forensicChainReference: payload.evidence.legalRuntime?.forensicChainReference || null,
    evidenceVerificationStatus: payload.evidence.legalRuntime?.evidenceVerificationStatus || null,
    legalRetentionNotice: payload.evidence.legalRuntime?.legalRetentionNotice || null,
    retentionClass: payload.evidence.legalRuntime?.retentionClass || null,
    archiveReference: payload.evidence.legalRuntime?.archiveReference || null,
    forensicVerificationReference: payload.evidence.legalRuntime?.forensicVerificationReference || null,
    judicialExportReference: payload.evidence.legalRuntime?.judicialExportReference || null,
    verificationIntegrityIndicator: payload.evidence.legalRuntime?.verificationIntegrityIndicator || null,
  });
}

export function buildInformedConsentEvidenceHtml(payload: InformedConsentEvidenceHtmlPayload): string {
  return renderInformedConsentTemplate(buildInformedConsentTemplatePayload(payload));
}