from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm
from pathlib import Path
from datetime import datetime, timezone
from typing import Any, Dict, Optional

GENERATED_DIR = Path("backend/generated")
GENERATED_DIR.mkdir(parents=True, exist_ok=True)


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)

def _normalize_payload(data: Optional[Dict[str, Any]], kwargs: Dict[str, Any]) -> Dict[str, Any]:
    payload: Dict[str, Any] = dict(data or {})
    payload.update(kwargs)

    if not payload.get("discharge_case_id"):
        payload["discharge_case_id"] = payload.get("order_id") or _utc_now().strftime("%Y%m%d%H%M%S")

    return payload


def generate_discharge_refusal_pdf(data: Optional[Dict[str, Any]] = None, **kwargs: Any) -> str:
    payload = _normalize_payload(data, kwargs)
    filename = f"refusal_{payload['discharge_case_id']}.pdf"
    filepath = GENERATED_DIR / filename

    c = canvas.Canvas(str(filepath), pagesize=A4)
    width, height = A4

    y = height - 25 * mm

    c.setFont("Helvetica-Bold", 16)
    c.drawString(20 * mm, y, "WathiqCare - Discharge Refusal Form")

    y -= 12 * mm
    c.setFont("Helvetica", 11)
    c.drawString(20 * mm, y, f"Generated At: {_utc_now().strftime('%Y-%m-%d %H:%M:%S')} UTC")

    y -= 12 * mm
    c.setFont("Helvetica-Bold", 12)
    c.drawString(20 * mm, y, "Case Information")

    y -= 8 * mm
    c.setFont("Helvetica", 11)
    lines = [
        f"Tenant Code: {payload.get('tenant_code', '')}",
        f"Patient MRN: {payload.get('patient_mrn', '')}",
        f"Patient Name: {payload.get('patient_name', '')}",
        f"User Email: {payload.get('user_email', '')}",
        f"Discharge Case ID: {payload.get('discharge_case_id', '')}",
        f"Status: {payload.get('status', '')}",
    ]

    for line in lines:
        c.drawString(20 * mm, y, line)
        y -= 7 * mm

    y -= 4 * mm
    c.setFont("Helvetica-Bold", 12)
    c.drawString(20 * mm, y, "Refusal Reason")

    y -= 8 * mm
    c.setFont("Helvetica", 11)

    refusal_reason = payload.get("refusal_reason", "")
    wrapped_lines = []
    words = refusal_reason.split()
    current_line = ""

    for word in words:
        test_line = f"{current_line} {word}".strip()
        if len(test_line) <= 90:
            current_line = test_line
        else:
            wrapped_lines.append(current_line)
            current_line = word
    if current_line:
        wrapped_lines.append(current_line)

    for line in wrapped_lines:
        c.drawString(20 * mm, y, line)
        y -= 7 * mm

    y -= 10 * mm
    c.setFont("Helvetica-Bold", 12)
    c.drawString(20 * mm, y, "Signer Information")

    y -= 8 * mm
    c.setFont("Helvetica", 11)
    signer_lines = [
        f"Signer Name: {payload.get('signer_name', '')}",
        f"Signer Role: {payload.get('signer_role', '')}",
        f"Signed At: {payload.get('signed_at', '')}",
        f"Signature Text: {payload.get('signature_text', '')}",
    ]
    for line in signer_lines:
        c.drawString(20 * mm, y, line)
        y -= 7 * mm

    y -= 10 * mm
    c.setFont("Helvetica-Bold", 12)
    c.drawString(20 * mm, y, "Acknowledgment")

    y -= 8 * mm
    c.setFont("Helvetica", 11)
    ack_lines = [
        "This document records that the patient refused discharge after medical advice.",
        "This PDF is generated by WathiqCare as part of the legal-medical evidence workflow.",
    ]
    for line in ack_lines:
        c.drawString(20 * mm, y, line)
        y -= 7 * mm

    y -= 18 * mm
    c.drawString(20 * mm, y, "Patient / Representative Signature: ________________________")

    y -= 12 * mm
    c.drawString(20 * mm, y, "Physician Signature: ______________________________________")

    y -= 12 * mm
    c.drawString(20 * mm, y, "Witness Signature: ________________________________________")

    c.showPage()
    c.save()

    return str(filepath)
