/**
 * PDF Core — Enterprise Bilingual PDF Rendering Engine
 *
 * Centralized PDF generation used by ALL platform modules.
 * Encapsulates: Puppeteer launch, A4 layout, watermark, QR, metadata block.
 *
 * Module-specific renderers pass HTML; this core handles browser lifecycle.
 */

import { PDF_CONFIG, IMC_BRANDING, LEGAL_CONFIG } from "@/lib/config/platform-config";
import {
  ENABLE_PDF_QR_CODE,
  ENABLE_PDF_WATERMARK,
  ENABLE_PDPL_NOTICES,
} from "@/lib/config/feature-flags";
import { computeDocumentChecksum } from "@/lib/core/audit-core";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type PdfLanguage = "ar" | "en" | "bilingual";

export type PdfCopyType = "PATIENT" | "MEDICAL" | "LEGAL";

export interface PdfRenderOptions {
  /** Language direction for the document */
  language?: PdfLanguage;
  /** Evidence copy classification */
  copyType?: PdfCopyType;
  /** Whether to apply watermark */
  watermark?: boolean;
  /** Whether to embed QR code */
  qrCode?: boolean;
  /** URL the QR code should point to */
  qrUrl?: string;
  /** Document reference for watermark label */
  documentRef?: string;
  /** Additional metadata for evidentiary block */
  evidenceMetadata?: PdfEvidenceMetadata;
}

export interface PdfEvidenceMetadata {
  checksum?: string;
  generatedByModel?: string;
  finalizedAt?: string;
  physicianId?: string;
  documentVersion?: string;
  tenantId?: string;
}

export interface PdfRenderResult {
  /** Raw PDF bytes */
  bytes: Buffer;
  /** SHA-256 checksum of bytes */
  checksum: string;
  /** Byte size */
  sizeBytes: number;
  /** Copy type rendered */
  copyType: PdfCopyType;
  /** Language rendered */
  language: PdfLanguage;
  /** Rendered at timestamp */
  renderedAt: string;
}

// ---------------------------------------------------------------------------
// Watermark HTML
// ---------------------------------------------------------------------------

export function buildWatermarkHtml(
  copyType: PdfCopyType,
  documentRef?: string
): string {
  if (!ENABLE_PDF_WATERMARK) return "";

  const labels: Record<PdfCopyType, { en: string; ar: string }> = {
    PATIENT: { en: "PATIENT COPY", ar: "نسخة المريض" },
    MEDICAL: { en: "MEDICAL RECORD COPY", ar: "نسخة السجل الطبي" },
    LEGAL: { en: "LEGAL ARCHIVE COPY", ar: "نسخة الأرشيف القانوني" },
  };

  const label = labels[copyType];
  const ref = documentRef ? ` · ${documentRef}` : "";

  return `
<div style="
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%) rotate(-35deg);
  font-size: 48px;
  font-weight: 900;
  color: rgba(0, 43, 92, ${PDF_CONFIG.watermarkOpacity});
  white-space: nowrap;
  pointer-events: none;
  z-index: 9999;
  font-family: 'Segoe UI', Arial, sans-serif;
  letter-spacing: 4px;
  text-align: center;
  line-height: 1.3;
">
  ${label.en}${ref}<br/>
  <span style="font-size: 30px;">${label.ar}</span>
</div>`;
}

// ---------------------------------------------------------------------------
// QR Code HTML (async)
// ---------------------------------------------------------------------------

export async function buildQrCodeHtml(url: string): Promise<string> {
  if (!ENABLE_PDF_QR_CODE || !url) return "";

  try {
    const QRCode = await import("qrcode");
    const dataUrl = await QRCode.toDataURL(url, {
      width: PDF_CONFIG.qrSize,
      errorCorrectionLevel: PDF_CONFIG.qrErrorCorrection,
      margin: 1,
    });
    return `
<div style="text-align:center; margin-top: 16px;">
  <img src="${dataUrl}" width="${PDF_CONFIG.qrSize}" height="${PDF_CONFIG.qrSize}" alt="QR verification" />
  <p style="font-size:9px; color:#666; margin-top:4px; font-family:monospace;">
    ${url}
  </p>
</div>`;
  } catch {
    return "";
  }
}

// ---------------------------------------------------------------------------
// Evidentiary Metadata Block
// ---------------------------------------------------------------------------

export function buildEvidenceMetadataBlock(meta: PdfEvidenceMetadata): string {
  const rows: Array<[string, string, string]> = [
    ["Checksum (SHA-256)", "بصمة المستند", meta.checksum ?? "—"],
    ["Generated By Model", "نموذج الإنشاء", meta.generatedByModel ?? "—"],
    ["Finalized At", "تاريخ الإتمام", meta.finalizedAt ?? "—"],
    ["Physician ID", "معرف الطبيب", meta.physicianId ?? "—"],
    ["Document Version", "إصدار المستند", meta.documentVersion ?? "—"],
  ];

  const rowsHtml = rows
    .map(
      ([en, ar, val]) => `
    <tr>
      <td style="font-size:8px;color:#555;padding:2px 8px;">${en} / ${ar}</td>
      <td style="font-size:8px;font-family:monospace;padding:2px 8px;">${val}</td>
    </tr>`
    )
    .join("");

  return `
<div style="margin-top:24px; border-top: 1px solid #ccc; padding-top: 12px;">
  <p style="font-size:9px;color:#888;font-weight:bold;margin-bottom:4px;">
    Evidentiary Metadata / البيانات الإثباتية
  </p>
  <table style="width:100%; border-collapse:collapse;">
    ${rowsHtml}
  </table>
  ${ENABLE_PDPL_NOTICES ? `
  <p style="font-size:7px;color:#aaa;margin-top:8px;border-top:1px solid #eee;padding-top:4px;">
    ${LEGAL_CONFIG.pdplNoticeEn}<br/>
    ${LEGAL_CONFIG.pdplNoticeAr}
  </p>` : ""}
</div>`;
}

// ---------------------------------------------------------------------------
// IMC Header HTML
// ---------------------------------------------------------------------------

export function buildImcHeaderHtml(language: PdfLanguage = "bilingual"): string {
  const showAr = language === "ar" || language === "bilingual";
  const showEn = language === "en" || language === "bilingual";

  return `
<div style="display:flex; align-items:center; justify-content:space-between; border-bottom:3px solid #002B5C; padding-bottom:12px; margin-bottom:20px;">
  <div>
    ${showEn ? `<div style="font-size:16px;font-weight:bold;color:#002B5C;">${IMC_BRANDING.fullName}</div>` : ""}
    ${showAr ? `<div style="font-size:15px;font-weight:bold;color:#002B5C;direction:rtl;">${IMC_BRANDING.fullNameAr}</div>` : ""}
    <div style="font-size:9px;color:#888;">${IMC_BRANDING.address}</div>
  </div>
  <div style="text-align:right;">
    <div style="font-size:11px;color:#C9A13B;font-weight:bold;">WathiqCare™</div>
    <div style="font-size:8px;color:#888;">Legal Workflow Platform</div>
  </div>
</div>`;
}

// ---------------------------------------------------------------------------
// Puppeteer Render
// ---------------------------------------------------------------------------

/**
 * Render HTML to PDF bytes using Puppeteer + Chromium.
 * Handles browser lifecycle, retries, and cleanup.
 *
 * @param html - Full HTML document string (must include <html>, <head>, <body>)
 * @param options - Render configuration
 */
export async function renderHtmlToPdf(
  html: string,
  options: PdfRenderOptions = {}
): Promise<PdfRenderResult> {
  const copyType = options.copyType ?? "MEDICAL";
  const language = options.language ?? PDF_CONFIG.defaultLanguage;
  const applyWatermark = options.watermark ?? true;
  const applyQr = options.qrCode ?? true;

  // Inject watermark
  let finalHtml = html;
  if (applyWatermark) {
    const watermarkHtml = buildWatermarkHtml(copyType, options.documentRef);
    finalHtml = finalHtml.replace("</body>", `${watermarkHtml}</body>`);
  }

  // Inject QR
  if (applyQr && options.qrUrl) {
    const qrHtml = await buildQrCodeHtml(options.qrUrl);
    finalHtml = finalHtml.replace("</body>", `${qrHtml}</body>`);
  }

  // Inject evidence metadata
  if (options.evidenceMetadata) {
    const metaHtml = buildEvidenceMetadataBlock(options.evidenceMetadata);
    finalHtml = finalHtml.replace("</body>", `${metaHtml}</body>`);
  }

  let pdfBytes: Buffer | null = null;
  let lastError: unknown;

  for (let attempt = 0; attempt <= PDF_CONFIG.chromiumMaxRetries; attempt++) {
    try {
      const chromium = await import("@sparticuz/chromium");
      const puppeteer = await import("puppeteer-core");

      const browser = await puppeteer.default.launch({
        args: chromium.default.args,
        defaultViewport: { width: PDF_CONFIG.viewportWidth, height: 1200 },
        executablePath: await chromium.default.executablePath(),
        headless: true,
      });

      try {
        const page = await browser.newPage();
        await page.setContent(finalHtml, { waitUntil: "domcontentloaded" });
        const raw = await page.pdf({
          format: PDF_CONFIG.format,
          margin: {
            top: `${PDF_CONFIG.margins.top}mm`,
            right: `${PDF_CONFIG.margins.right}mm`,
            bottom: `${PDF_CONFIG.margins.bottom}mm`,
            left: `${PDF_CONFIG.margins.left}mm`,
          },
          printBackground: PDF_CONFIG.printBackground,
        });
        pdfBytes = Buffer.from(raw);
      } finally {
        await browser.close();
      }

      break; // success
    } catch (err) {
      lastError = err;
      if (attempt < PDF_CONFIG.chromiumMaxRetries) {
        await new Promise((r) => setTimeout(r, 500 * (attempt + 1)));
      }
    }
  }

  if (!pdfBytes) {
    throw new PdfRenderError(
      "PDF rendering failed after retries.",
      lastError
    );
  }

  const checksum = computeDocumentChecksum(pdfBytes);

  return {
    bytes: pdfBytes,
    checksum,
    sizeBytes: pdfBytes.length,
    copyType,
    language,
    renderedAt: new Date().toISOString(),
  };
}

// ---------------------------------------------------------------------------
// Error
// ---------------------------------------------------------------------------

export class PdfRenderError extends Error {
  readonly code = "PDF_RENDER_FAILED" as const;
  constructor(message: string, public readonly cause?: unknown) {
    super(message);
    this.name = "PdfRenderError";
  }
}
