BEGIN;

ALTER TABLE secure_discharge_links
  ADD COLUMN IF NOT EXISTS otp_hash VARCHAR NULL,
  ADD COLUMN IF NOT EXISTS otp_expires_at TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS otp_attempts VARCHAR NULL DEFAULT '0',
  ADD COLUMN IF NOT EXISTS otp_locked_until TIMESTAMP NULL;

COMMIT;
